### ISSUE TITLE
Compilation buffer sometimes ignores compilation-scroll-output

### ISSUE THREAD

**Issue by TatriX** [brotzeit/rustic#101]
Compilation scroll behavior seems to randomly break.
After a cold start it respects `(setq compilation-scroll-output nil)` but then after some random event which I can't yet trace, ignores it. After that I have to kill *rustic-compilation* buffer to make it work again.

**Comment by brotzeit** [comment]
I have to admit that I just added some ugly code that seemed to work for this. I've been planning to do this properly.

**Comment by brotzeit** [comment]
I've tried to get this right with `set-window-point` and `set-window-start`, but I just can't get this to work. Would it be problem to kill and regenerate the compilation buffer every time when running a compilation command ? It seems killing the buffer solves the problem ? I would still try to find a different solution, but this would fix it at least temporarily.

**Comment by brotzeit** [comment]
I've tried to change window points in the process filter and it seems to work like the former code. But I have no idea if this also breaks when reusing an existing compilation buffer.
https://github.com/brotzeit/rustic/commit/6e2fbd1e1aafb926d455d15f9aeb3711205c84af

**Comment by brotzeit** [comment]
I think this should be fixed by 6e2fbd1. If not, please reopen the issue.
