### ISSUE TITLE
Adding support for rustic-mode in Flycheck

### ISSUE THREAD

**Issue by cpitclaudel** [brotzeit/rustic#106]
Hi there,

Right now we only enable Flycheck's rust checkers for rust-mode; should we enable them for rustic as well?

cc @fmdkdd 

Thanks for your work!

**Comment by brotzeit** [comment]
Hey, thanks for asking! Most rustic users are using lsp-mode with its generic checker, so users who want to use the "old" checkers have to activate them themselves. Flycheck currently enables the checkers for rust-mode by default right ?

**Comment by cpitclaudel** [comment]
>  Flycheck currently enables the checkers for rust-mode by default right ?

Correct

**Comment by brotzeit** [comment]
Given that most rustic users(in contrast to rust-mode users I guess) use flycheck with lsp-mode, I think it's better to let the user manually activate the existing checker in rustic(I added it years ago). But thanks again, I really appreciate it.
