### ISSUE TITLE
Compile buffer fails to recognise errors to provide jump to

### ISSUE THREAD

**Issue by phillord** [brotzeit/rustic#110]
This seems to happen fairly frequently to me. Often enough that I am surprised that no one else has mentioned it. Or, more likely, it is only happening to me. 

Is it a known issue?

**Comment by brotzeit** [comment]
Do you mean when you click on it or when running next-error or compilation-next-error ?

**Comment by phillord** [comment]
They are the same thing are they not? I do see this working some times. For example, in this error:

````
error[E0425]: cannot find value `fdafsd` in this scope
   --> src/io/rdf/reader3.rs:421:9
    |
421 |         fdafsd
    |         ^^^^^^ not found in this scope
````

the `--> reader3.rs` line is clickable. But other times it comes up as not. I will see if I can hunt this down with a reproduction.

More generally, it would be nice to make the all the line numbers clickable. In this example, for instance, 

````
error[E0061]: this function takes 0 arguments but 1 argument was supplied
   --> src/io/rdf/reader3.rs:421:14
    |
331 |     fn headers(&mut self) {
    |     --------------------- defined here
...
421 |         self.headers(self.bnode);
    |              ^^^^^^^ ---------- supplied 1 argument
    |              |
    |              expected 0 arguments
````

I can get to line 421 by clicking, but not 331. But you might validly fix this error at either location.

**Comment by brotzeit** [comment]
> They are the same thing are they not?

`next-error` makes use of `next-error-function`. It seems flycheck sets the function `flycheck-next-error-function`. In compilation-mode the value is `compilation-next-error-function`.

`compile-goto-error` is triggered by mouse I think. It seems to directly use the text property at point.

**Comment by brotzeit** [comment]
> I can get to line 421 by clicking, but not 331. But you might validly fix this error at either location.

Hmmm, I will take a look at it.

**Comment by mookid** [comment]
Another reason why it would be a nice idea to make rustic properly integrate rust-mode as a dependency :)

**Comment by brotzeit** [comment]
I used a hook to make this possible. But this looks better to me. Hooks should be avoided when possible right ?

Regarding making rustic depend on rust-mode, I still wonder if it would be confusing for users when there are different functions for the same purpose like rustfmt. Maybe rustic and rust-mode can use the same name for this functions, hmmmm.

**Comment by mookid** [comment]
> Regarding making rustic depend on rust-mode, I still wonder if it would be confusing for users when there are different functions for the same purpose like rustfmt. Maybe rustic and rust-mode can use the same name for this functions, hmmmm.

I think that rustic should be free to define whichever function it want, and let the users choose.
The confusion comes precisely from the usage of the same name imo. 

Without going into super general considerations: the support for existing emacs infrastructure (syntax highlighting, compile.el, ....) is there in rust-mode and could be reused rather than reinvented (and bugs related to these could go to one place).

**Comment by brotzeit** [comment]
I couldn't reuse the existing facilities since most of the features I added on top are not possible without reinventing some stuff. I've used compile.el where it was possible. I know you aren't interested in the features that I've added, but some people are. However it certainly can be done better than I did =)

**Comment by stsquad** [comment]
So I noticed this today as I do all my compiling via counsel-compile but of course you locally bind the alist options for rustic-compile triggered buffers. There is a worry about having overly long lists of regexes if you have very big compile buffers but this should probably be solved by just tweaking compilation-error-regexp-alist. FWIW I've temporarily patched this in my config:

    (use-package rustic
      :ensure t
      :config (progn (add-to-list 'compilation-error-regexp-alist-alist
                                  (cons 'rustic-error rustic-compilation-error))
                     (add-to-list 'compilation-error-regexp-alist-alist
                                  (cons 'rustic-warning rustic-compilation-warning))
                     (add-to-list 'compilation-error-regexp-alist-alist
                                  (cons 'rustic-info rustic-compilation-info))
                     (add-to-list 'compilation-error-regexp-alist-alist
                                  (cons 'rustic-panic rustic-compilation-panic))

                     (add-to-list 'compilation-error-regexp-alist 'rustic-error)
                     (add-to-list 'compilation-error-regexp-alist 'rustic-warning)
                     (add-to-list 'compilation-error-regexp-alist 'rustic-info)
                     (add-to-list 'compilation-error-regexp-alist 'rustic-panic)))

And later in my compile-mode tweaks:

    (use-package compile
      :bind (("C-c c" . counsel-compile)
             ("C-c r" . recompile)
             (:map compilation-mode-map
                   ("n" . compilation-next-error)
                   ("p" . compilation-previous-error)))
      :diminish ((compilation-in-progress . "*COM*"))
      :config
      (progn
        (setq
         compilation-auto-jump-to-first-error nil
         compilation-scroll-output t
         compilation-window-height 10
         counsel-compile-make-args (format "-j%d" (+ 1 my-core-count)))
        (add-to-list
         'compilation-error-regexp-alist-alist
         (list 'tsan my-tsan-compilation-mode-regex 1 2 nil 0))
        (add-to-list 'savehist-additional-variables 'compile-history)
        (add-to-list 'savehist-additional-variables 'counsel-compile-history)
        ;; lets not overtax the regex match on our huge compilation buffers
        (when I-am-at-work
          (setq compilation-error-regexp-alist '(gcc-include gnu tsan
                                                             rustic-error rustic-warning rustic-info rustic-panci)))
        ;; Detect stalls
        (add-hook 'compilation-filter-hook
                  #'my-compilation-mode-warn-about-prompt)
        ;; Add tracking to the compilation buffer
        (with-eval-after-load 'tracking
          (add-hook 'compilation-start-hook 'my-hide-compilation-buffer)
          (add-hook 'compilation-finish-functions 'my-report-compilation-finished))))

**Comment by brotzeit** [comment]
-> #355

**Comment by brotzeit** [comment]
I'm really motivated to fix this once and for all and already took a closer look at the parse functions of compile.el. But I actually have issues to find a situation where the parsing fails. It also seems the tests I've added years ago don't fail anymore.

Can somebody give me a hint before I forget what I looked up the last days =)

Please comment in #355
