### ISSUE TITLE
Don't break goto search result and goto error for other languages

### ISSUE THREAD

**Issue by tarsius** [brotzeit/rustic#114]
I finally figured out an issue that has been driving me crazy for months. After some time going to a match from e.g. a `*grep*` or `*Compile-Log*` buffers just stopped working even though the relative file-name of the search result as well as the displayed and effective `default-directory` of the buffer are correct.

Turns out it stops working once `rustic` has been loaded and has established its advice to forcefully let-binds `default-directory` to the root of the current project. That's nasty. It might be the correct thing to do for rust. For many many other things it obviously is not.

I recommend you give up on "fixing" the `default-directory` after the fact. If `cargo` spits out paths that are relative to the root of the project even when invoked from a subdirectory, then adjust the `default-directory` **before** calling `cargo`. e.g. by doing the let-binding around that call *and nothing else*.

**Comment by tarsius** [comment]
> It might be the correct thing to do for rust.

#110 suggests that it might not even be appropriate here.

**Comment by brotzeit** [comment]
Yeah, sorry about that. I remember that I wanted to fix this....
There's another hook that has to be fixed...

**Comment by brotzeit** [comment]
I just removed it for now.

**Comment by dalepsmith** [comment]
Yey!  I've been trying to track down why grep breaks for me and just today I found rustic installing a hook that messes with default-directly.

Glad to see this fixed!  Thanks.

**Comment by brotzeit** [comment]
I really need somebody reviewing my PRs =)
