### ISSUE TITLE
Allow rustfmt configuration from Emacs

### ISSUE THREAD

**Issue by Janfel** [brotzeit/rustic#117]
It would be nice if there were a way to specify arguments to `rustfmt` through a variable.
This would allow the user to make `rustfmt` follow `indent-tabs-mode` or to experiment with formatting options without needing a `.rustfmt.toml`.

**Comment by Janfel** [comment]
As `rustfmt` doesn’t provide many arguments, the main functionality could be provided by a `rustic-rustfmt-style-alist` of `(symbol . value)` pairs that is used to set the `--config` argument if not `nil`.

**Comment by brotzeit** [comment]
Or maybe just a string of parameters that's passed to rustfmt ? Sounds simpler.

**Comment by Janfel** [comment]
As `rustic-format-start-process`, `rustic-make-process` and `make-process` itself take `:command` as a list of strings, I believe a list of string parameters to be a vastly better solution that a single string of parameters. My idea of using an alist for style parameters could still be implemented by the user with advice.

**Comment by brotzeit** [comment]
Can you provide a PR ?
