### ISSUE TITLE
Show macro expansion

### ISSUE THREAD

**Issue by brotzeit** [brotzeit/rustic#12]
It seems intellij has this feature, but I have no idea how they did it. I only found this command `cargo rustc -- -Zunstable-options --pretty=expanded` to get expanded macros, however I can't imagine they are parsing this output. If anybody knows how this works would be great.

**Comment by mgxm** [comment]
I don't know how the Intellij feature works, but there's a crate that does
exactly it, [cargo-expand](https://github.com/dtolnay/cargo-expand). I used it once to debug some
nom macros and it worked perfetcly

**Comment by brotzeit** [comment]
Yeah I also found this but there is a note: 

> 
> This is a wrapper around the more verbose compiler command:
> 
> $ cargo rustc --profile=check -- -Zunstable-options --pretty=expanded

Did you also use this on a bigger project ?

**Comment by brotzeit** [comment]
https://github.com/emacs-lsp/lsp-mode/pull/1266
