### ISSUE TITLE
saner defaults for compilation faces?

### ISSUE THREAD

**Issue by mohkale** [brotzeit/rustic#123]
Seems to be that [all](https://github.com/brotzeit/rustic/blob/master/rustic-compile.el#L63) of the special faces for rustic-compilation-mode inherit from default, meaning by default you get a really bland compilation buffer. They should inherit from the appropriate compilation faces instead.

So
| rustic-face | compilation-face |
|---|---|
| rustic-compilation-warning | compilation-warning |
| rustic-compilation-info | compilation-info |
| rustic-compilation-error | compilation-error |
| rustic-compilation-column | compilation-column-number |
| rustic-compilation-line | compilation-line-number |

S.N. I didn't even realize you could jump to line numbers/errors until I tried to.

**Comment by brotzeit** [comment]
I think the idea was to make the colors that are emitted by cargo the default. Default compile.el doesn't translate control sequences so I thought rustic should use different defaults.
Any ideas how to improve the docs ? I apprecaite any help I can get, since I currently don't even use rust.

**Comment by mohkale** [comment]
I see. #127 seems fine then.
