### ISSUE TITLE
Is there a way to run `rustic-cargo-run` interactively

### ISSUE THREAD

**Issue by zoechi** [brotzeit/rustic#124]
so that I can enter input to a command line application I'm building.
I think https://emacs.stackexchange.com/questions/51156/cargo-process-does-not-accept-user-input is about the same question.
Using `cargo.el` seems a bit redundant because rustic seems to provide a lot of that already.

**Comment by zoechi** [comment]
Changing the suggestion from the SO answer to

```lisp
(with-eval-after-load 'rust-mode
  (define-key rust-mode-map (kbd "C-r") 'my-cargo-run))
(defun my-cargo-run ()
  "Build and run Rust code."
  (interactive)
;;  (cargo-process-run)
   (rustic-cargo-run) 
  (let (
      (orig-win (selected-window))
      (run-win (display-buffer (get-buffer "*Cargo Run*") nil 'visible))
    )
    (select-window run-win)
    (comint-mode)
    (read-only-mode 0)
    (select-window orig-win)
  )
)
```
seemed to be enough.

Perhaps still worth considering adding something like this to rustic.

**Comment by brotzeit** [comment]
Is this ok for you #126 ?

**Comment by zoechi** [comment]
Yes, that would do. 
I there a reason not to make it a comint buffer? (just curious)

**Comment by brotzeit** [comment]
Why would you want the compilation buffer be in comint-mode ? It's just about sending some input to the process right ? There will also be issues if you want it to work correctly after you entered your input.

**Comment by zoechi** [comment]
With the code above it's like running like in a shell which is convenient for developing interactive command line apps.
I don't know much about Emacs yet. How would it not run correctly this way?

**Comment by brotzeit** [comment]
Example:

If you want to use `compilation-next-error` in comint-mode this won't work because you have a check in the function that will complain about it:
```

(defun compilation-next-error (n &optional different-file pt)
  "Move point to the next error in the compilation buffer.
This function does NOT find the source line like \\[next-error].
Prefix arg N says how many error messages to move forwards (or
backwards, if negative).
Optional arg DIFFERENT-FILE, if non-nil, means find next error for a
file that is different from the current one.
Optional arg PT, if non-nil, specifies the value of point to start
looking for the next message."
  (interactive "p")
  (or (compilation-buffer-p (current-buffer))
      (error "Not in a compilation buffer"))
```

**Comment by brotzeit** [comment]
But if it's that important for you it would be possible to make a mode that's only being used by cargo-run ?

**Comment by zoechi** [comment]
"Important" is a strong word. I'm at the beginning of the process in figuring out a good workflow for Emacs with Rust, with little to no knowledge in both.
I'll just experiment with above hack and your recent change and see how it works.
Thanks a lot for your support <3

**Comment by l2dy** [comment]
Hi, I'm a beginner in Rust and I'm following the guessing game tutorial in [the book](https://doc.rust-lang.org/book/ch02-00-guessing-game-tutorial.html).

In the tutorial, users would enter a number on each guess. With `rustic-compile-send-input`, I have to run the function on each guess, which is not so convenient for an interactive program.

IMHO, `cargo run` should focus on running the program rather than finding errors from compilation, which is taken care of in `cargo check` or `cargo build`. So it makes sense to let `rustic-cargo-run` use a separate buffer.

**Comment by brotzeit** [comment]
Can you please open a ned issue.
