### ISSUE TITLE
Rustfmt error buffer is shown even when no formatting error happened

### ISSUE THREAD

**Issue by nsavch** [brotzeit/rustic#130]
Apparently this commit https://github.com/brotzeit/rustic/commit/ce73c4cfa793e26c1eca245105d7bb4e12d060bb introduced this bug. When I have `rustic-format-on-save` set to `t` and save a syntactically correct file emacs still shows the rustfmt buffer like there was an error. The rustfmt buffer is completely empty.

**Comment by brotzeit** [comment]
Yeah, I didn't review a recent PR properly, again...

I will push a fix today.

**Comment by brotzeit** [comment]
Please test #131.

**Comment by nsavch** [comment]
works perfectly for me! (I tested both syntactically correct and syntactically incorrect cases).
