### ISSUE TITLE
Highlighting syntax errors in integration tests

### ISSUE THREAD

**Issue by felix-clark** [brotzeit/rustic#135]
Syntax errors in integration tests (i.e. `tests/*.rs`) don't show up via flycheck because the check command `cargo check` does not cover these by default. Changing this may be as simple as using `cargo check --tests` in `rustic-cargo-check` (replacing `cargo check`), but I won't pretend to understand any potential complications there.

**Comment by brotzeit** [comment]
`rustic-cargo-check` and the flycheck checker are two different things. The former opens a compilation buffer that displays the output of 'cargo check'. The default rustic flycheck checker uses clippy.

Maybe you are using the lsp-mode checker ? Try to add the parameter to `lsp-rust-analyzer-cargo-watch-command`, but I don't know if it works.

**Comment by felix-clark** [comment]
Thanks for clarifying; yes, I am using the lsp-mode checking. It's actually `lsp-rust-analyzer-cargo-watch-args` that can be set to, for instance, `["--all-targets"]`. This gives me syntax highlighting in integration test code, although it seems a little slower and possibly a bit inconsistent.

Is this something that can or should be addressed in rustic? There might also be a performance concern in making the checker cover more ground by default.

**Comment by brotzeit** [comment]
Hmmm, it's actually a default for rls in lsp-mode. If we change this, the default should be changed in lsp-mode and not in rustic IMO. Give me some time to think about it. However I don't like the fact that it has negative impact on the performance...

**Comment by cassandracomar** [comment]
I've been trying to get this to work for a while. it seems like rust-analyzer, code completion, etc. all work fine within tests but the flycheck/cargo watch output from lsp never show up. what I'm working with right now:

```elisp
  (setq lsp-rust-analyzer-cargo-watch-enable t)
  (setq lsp-rust-analyzer-cargo-all-targets t)
  (setq lsp-rust-analyzer-cargo-watch-command "clippy")
  (setq lsp-rust-analyzer-cargo-watch-args ["\"--all-features\"" "\"--tests\""])
  (setq rustic-flycheck-clippy-params "--message-format=json --all-features --tests")
  (push 'rustic-clippy flycheck-checkers)
```

obviously this is turning on clippy from both rustic and lsp but I'm kinda just hoping one of them gets run against test buffers -- even with this set, neither does. whereas I can confirm from the shell that `cargo clippy --all-features --tests` does indeed report errors within test modules.

**Comment by brotzeit** [comment]
I guess this should be the default value, so let's see if people complain about performance issues.
