### ISSUE TITLE
Integrate rustdoc-to-org

### ISSUE THREAD

**Issue by samhedin** [brotzeit/rustic#137]
Would it be of interest to integrate [rustdoc-to-org](https://github.com/samhedin/rustdoc-to-org) with rustic?
 # Advantages

* If someone is using Rustic, there is a good chance that they would like to browse documentation inside Emacs.
* Having them both in the same repo would make setup and discovery easier for those users.
* A smooth doc reading experience (not saying that rustdoc-to-org is there yet), would be a big + for the project itself - using Rustic would far outclass the Rust experience of any other editor, even more than it already does.
* The project is still in an early state, and it is the first time I write elisp, so there is still lots to do and improve. However, merging with rustic would be a good way for rustdoc to get feedback - living inside this project would make rustdoc itself better than it could be on its own.

# Disadvantages

## Would make the setup more difficult
Rustdoc requires some third party tools.

* Pandoc
* Ripgrep
It would be possible to make this optional, and default to grep or vice versa. However, adding customization for this and relying on the user to select the option that works for them is probably as much work for the user as installing rg.
* cargo-makedocs https://github.com/Bunogi/cargo-makedocs
`cargo doc` generates a ridiculous amount of (most likely) unwanted documentation, which adds a lot of time to batch conversion and bloats up the search results.

## Other

* The job of parsing like this is hard to get completely right. I would not expect the converted .org files to ever look 100% correct - but 90 - 95% should be possible. 
* Batch conversion is annoying - It takes time and locks Emacs. I am working on making the process smoother but haven't found a method I am satisfied with yet.

# Alternatives
* Leave it as it is today - two happy projects working to make the rust emacs experience the best in town.

# Questions
* Do you have any general comments or feedback regarding the current state of rustdoc?
* What changes would you like to see before considering merging in rustdoc?
* Do you see any advantages or disadvantages that I have not listed?

**Comment by brotzeit** [comment]
Sounds like a good idea! I generally think it's good to have most rust related functionality in one package. Especially new users are often overwhelmed by the amount of emacs packages and all the possibilities. Since the package requires non emacs tools, it would be better to make this feature optional. You can open a pull request whenever you think it's ready.

Another possibility to get more feedback is to ask the doom community if they are interested in this feature. I think most rustic users come from doom-emacs.

**Comment by samhedin** [comment]
Cool! I'll see if rustdoc can get some more feedback from users. Once it's been given some more time to sit in its own repo and mature, I'll make the PR. :rocket:
