### ISSUE TITLE
possible to override spinner type for the modeline?

### ISSUE THREAD

**Issue by mattsawyer77** [brotzeit/rustic#142]
Hello, this is definitely a very minor/low-priority issue. But would it be possible to override the spinner type? the current horizontal one looks a bit jarring with a proportional modeline font.

**Comment by brotzeit** [comment]
Hi. I added a note to the readme.

**Comment by mattsawyer77** [comment]
@brotzeit thanks for the quick response! FYI I tried customizing the spinner type, but it seems my issue was that lsp-mode was overriding it and it seems to hardcode it to `progress-bar`. I tried tweaking lsp-mode and overriding it there worked. But perhaps overriding `rustic-spinner-type` would work for non-lsp rustic users?

**Comment by brotzeit** [comment]
rustic displays its own spinner when running org-babel or certain cargo processes. I thought you were talking about this. 

It seems lsp-mode doesn't allow customizing the spinner type. I would suggest to open an issue or even better open a pull request there.
