### ISSUE TITLE
helm-ag should be optional for rustdoc

### ISSUE THREAD

**Issue by brotzeit** [brotzeit/rustic#143]
We need a defcustom to define which command is to be used to run ripgrep.

**Comment by brotzeit** [comment]
It would also be good to mention that lsp-mode is required for this feature. Even better would be if it also would work with eglot.

**Comment by brotzeit** [comment]
It would be ideal if it would also be usable with a command that's provided by emacs. Generally it's always good to reduce hard dependencies.

**Comment by brotzeit** [comment]
@samhedin this issue can be closed right ?

**Comment by samhedin** [comment]
Yes, this can be closed. I will continue to work on making the installation easier, but the time I have is spontaneous at the moment since school started again. Looking forward to it though :)
