### ISSUE TITLE
Feature Request: Integration with Cargo Edit

### ISSUE THREAD

**Issue by thor314** [brotzeit/rustic#145]
This exists: https://lib.rs/crates/cargo-edit

which manages the .toml file nicely. `Rust-mode` comes packaged with `cargo-edit` commands. Easy ask would be to integrate `rustic mode` with pre-packaged keybinds. 
Slightly more involved ask would be to have `rustic-mode` run cargo add on any packages mentioned in the `use blah` list.

**Comment by brotzeit** [comment]
I suppose you mean https://github.com/kwrooijen/cargo.el/commit/e4cbedee11676108719651ace8767c24473b44a8

**Comment by brotzeit** [comment]
> rustic-mode run cargo add on any packages mentioned in the use blah list.

Sorry but I don't get what you mean.

**Comment by thor314** [comment]
Cool, nice pull request
I meant something like, if I type something like (borrowed from a proc macro file I'm working on)
```
use proc_macro::TokenStream;
use quote::{quote, quote_spanned};
use syn::{parse_macro_input, DeriveInput};
use syn::spanned::Spanned;
use deriving::{struct_fields, has_attribute};
```
rustic-mode checked to see if the toml already had `syn, deriving, quote, proc_macro`, checked if `cargo-add` was available, and called `cargo-add syn deriving quote proc_macro whatever_else_is_missing` if appropriate.

**Comment by brotzeit** [comment]
Hmmm, yes that is probably not too hard. However it feels like this should be provided by 'cargo add' as a parameter. Although it wouldn't hurt to have a few lisp functions until `cargo-edit` provides this feature.
