### ISSUE TITLE
cargo-add: add feature to automatically detect missing dependencies

### ISSUE THREAD

**Issue by brotzeit** [brotzeit/rustic#150]
The idea is to parse crates from use statements(in the current buffer) and look them up in Cargo.toml. Then the user could get a minibuffer prompt containing the missing dependencies similar to `Add missing dependencies: cargo add crate1 crate2 crate3`.

#145

**Comment by samhedin** [comment]
Would it be easier to rely on the `unresolved import` error rather than parsing manually?
This would require the user to have a language server, of course.

**Comment by brotzeit** [comment]
Sounds reasonable. Most people use lsp anyway.

**Comment by samhedin** [comment]
Closing this as #161 was merged.

**Comment by brotzeit** [comment]
Unfortunately we can't merge this until it also supports eglot or it will only be loaded when lsp-mode is present.

**Comment by samhedin** [comment]
You're right, I was too quick on the trigger. I'll take a look at eglot support!

**Comment by brotzeit** [comment]
Should be working now.
