### ISSUE TITLE
When set rustic-format-trigger to  'on-complation, format does not working when run `rustic-recompile`.

### ISSUE THREAD

**Issue by zw963** [brotzeit/rustic#151]
Thank you for offer this awesome emacs mode.

In fact,  most of feautre is just working, the only issue is, i expect to format 
before run `rustic-compilation`,  but it never be triggered.

Following is my config:

```el
(require 'rustic)
(setq rustic-format-on-save nil)
(setq buffer-save-without-query t)
(setq rustic-format-trigger 'on-compile)
(setq compilation-read-command nil)

(setq lsp-rust-analyzer-cargo-watch-command "clippy")
(push 'rustic-clippy flycheck-checkers)
(setq rustic-flycheck-clippy-params "--message-format=json")
```

What i expected is:

When i press `Ctrl+C Ctrl+C TAB` to run `rustic-compilation`,  it format my
code before compilation.

BTW:

1. if set to `on-save`, it is working.
2. run `rustic-format-buffer` works.

Thank you

**Comment by brotzeit** [comment]
> (setq rustic-format-on-save nil)

this variable is deprecated so you don't have to set it

> (push 'rustic-clippy flycheck-checkers)

If you are using lsp-mode you should not activate this checker.

Are you using doom-emacs, spacemacs or something similiar ?

**Comment by brotzeit** [comment]
Just to be sure, you are actually using the command `rustic-compile` to trigger compilation ?

**Comment by zw963** [comment]
> Are you using doom-emacs, spacemacs or something similiar ?

No.


> > (push 'rustic-clippy flycheck-checkers)

> If you are using lsp-mode you should not activate this checker.

Yes, i us lsp-mode, it's works fine, i can see many useful info from window right side.
But, i prefer to show the flycheck red underline below the buffer content too, 

as below:

![image](https://user-images.githubusercontent.com/549126/94328663-ed7a5600-ffe6-11ea-9847-1e00ba57f680.png)

if i am not add following three line code,  it not show the underline.

```el
(setq lsp-rust-analyzer-cargo-watch-command "clippy")
(push 'rustic-clippy flycheck-checkers)
(setq rustic-flycheck-clippy-params "--message-format=json")
```

![image](https://user-images.githubusercontent.com/549126/94328746-91640180-ffe7-11ea-8ba5-f6905976e76f.png)

What i means is, can i add flycheck red underline feature back, as original `(rust-mode)` done?


> Just to be sure, you are actually using the command rustic-compile to trigger compilation ?

Oh, my fault! in fact, i think i run `rustic-recompile` instead of `rustic-compile`.

**Comment by brotzeit** [comment]
You need only this `(setq lsp-rust-analyzer-cargo-watch-command "clippy")` when you are using lsp-mode for flycheck.

> Oh, my fault! sorry, i think i run rustic-recompile instead of rustic-compile, latter is working now!

It should also work for `rustic-recompile`. I found the problem and will push a fix, thanks.

**Comment by zw963** [comment]
> You need only this (setq lsp-rust-analyzer-cargo-watch-command "clippy") when you are using lsp-mode for flycheck.

Yes, i replace 
```cl
setq lsp-rust-analyzer-cargo-watch-command "clippy")
(push 'rustic-clippy flycheck-checkers)
(setq rustic-flycheck-clippy-params "--message-format=json")
```

With

```cl
setq lsp-rust-analyzer-cargo-watch-command "clippy")
;; (push 'rustic-clippy flycheck-checkers)
;; (setq rustic-flycheck-clippy-params "--message-format=json")
```

But, as i describe in previous comment, can i know why following red underline for flycheck is missing?

![image](https://user-images.githubusercontent.com/549126/94337922-b2951400-0020-11eb-9ea9-67eab0b2bcfd.png)

Is there another way to enable flycheck as done like `rust-mode` ?

Thank you.

**Comment by brotzeit** [comment]
This `(push 'rustic-clippy flycheck-checkers)` enables the non-lsp flycheck checker.

This `(setq lsp-rust-analyzer-cargo-watch-command "clippy")` configures lsp-mode to use clippy. If you don't get clippy warnings this way you have to look at the lsp log. Please first upgrade the emacs packages.

**Comment by zw963** [comment]
> This (push 'rustic-clippy flycheck-checkers) enables the non-lsp flycheck checker.

Hi, i guess i am not describe clearly for my issue.

Following screenshot all use same lsp-mode config,  same flycheck config.

But, as you can see, Following ruby-mode buffer, we can see flycheck mark 
the `return` with a green underline, and show some message on minibuffer.
this behavior is what i expected, if i use `rust-mode`, it behavior same too.

![image](https://user-images.githubusercontent.com/549126/94344383-7332eb80-0051-11eb-91d5-62faf9031c45.png)

But when i switch to use rustic,  the underline is missing, instead,  it show flycheck message 
on the right by `lsp-ui` package.

![image](https://user-images.githubusercontent.com/549126/94344380-6dd5a100-0051-11eb-8cc8-8ec55f3c256c.png)

My question is, how can i show rust error message the old way(underline) instead of the fancy lsp-ui
new way?

I consider this is not a lsp-mode issue, i guess rustic disable some flycheck default display behavior,  and use lsp-ui replace it, right?

Thank you.

**Comment by brotzeit** [comment]
> My question is, how can i show rust error message the old way(underline) instead of the fancy lsp-ui
new way?

flycheck and lsp-ui do not exclude each other in this regard.

> I consider this is not a lsp-mode issue, i guess rustic disable some flycheck default display behavior, and use lsp-ui replace it, right?

That's not the case.

Let me think about it, but the probability that this is related to your config is very high. I suggest that you try it with a config that only contains lsp-mode and rustic and check the lsp log. My guess is that lsp-mode(rust-analyzer ?) can't run clippy for some reason. This is a common issue for users, since there are many possible reasons.

**Comment by zw963** [comment]
@brotzeit , oh, sorry for confusing, i guess i do know why now.

After i add following lsp-mode config, anyway, underline start to works now.

```el
(require 'lsp-diagnostics)  ;;  i am not require it manually before.
(setq lsp-ui-sideline-show-diagnostics nil)
```

![image](https://user-images.githubusercontent.com/549126/94346415-14746e80-005f-11eb-89b9-d3db2fd613bc.png)

Thank you very much for help.

**Comment by brotzeit** [comment]
Hmmm, this shouldn't be necessary though.

**Comment by zw963** [comment]
> Hmmm, this shouldn't be necessary though.

Okay, following is all my related config,  please check anyway if you think this is a issue, perhaps i do something wrong? haha

### lsp-mode_init.el

```cl
(require 'lsp-mode)
(require 'lsp-completion)
(require 'lsp-diagnostics)
(require 'lsp-modeline)
(lsp-modeline-diagnostics-mode 1)
(setq lsp-modeline-diagnostics-scope :project)

(require 'lsp-ui)
(setq lsp-ui-sideline-delay 0.5) ;; default 0.2
(setq lsp-ui-sideline-show-diagnostics nil)
(setq lsp-ui-sideline-show-hover t)

(setq lsp-enable-file-watchers nil)

(define-key lsp-ui-mode-map [remap xref-find-definitions] #'lsp-ui-peek-find-definitions)
(define-key lsp-ui-mode-map [remap xref-find-references] #'lsp-ui-peek-find-references)

(require 'lsp-headerline)
(lsp-headerline-breadcrumb-mode 1)
(provide 'lsp-mode_init)

;;; lsp-mode_init.el ends here
```

### rustic_init.el

```cl
(require 'rustic)

(setq buffer-save-without-query t)
(setq rustic-lsp-format t)
(setq rustic-format-trigger 'on-compile)
(setq compilation-read-command nil) ;; not prompt on minibuffer when do compile.
(setq lsp-rust-analyzer-cargo-watch-command "clippy")

(define-key rustic-compilation-mode-map [(super n)] 'compilation-next-error)
(define-key rustic-compilation-mode-map [(super p)] 'compilation-previous-error)
(define-key rustic-mode-map [(control c) (control c) (control c)] 'rustic-format-buffer)

(defun my-rustic-hook ()
  (setq-local company-idle-delay 0.0))

(add-hook 'rustic-mode-hook 'my-rustic-hook)

(with-eval-after-load 'popwin
  (setq rustic-compile-display-method 'pop-to-buffer)
  (add-to-list 'popwin:special-display-config '(rustic-compilation-mode :noselect t)))

(provide 'rustic_init)

;;; rustic_init.el ends here
```

**Comment by zw963** [comment]
@brotzeit , one more question, sorry, if we have `(rustic-recompile)`, why we still need `(rustic-compile)` ?
can we only keep recompile ? I am a rust newcomer, sorry for annoy you again : )

**Comment by brotzeit** [comment]
No problem. It's similiar to `recompile`. If you use rustic-compile with `C-u` the argument gets stored in `compilation-arguments`. You can rerun compilation with this argument with `rustic-recompile`.

**Comment by zw963** [comment]
> No problem. It's similiar to `recompile`. If you use rustic-compile with `C-u` the argument gets stored in `compilation-arguments`. You can rerun compilation with this argument with `rustic-recompile`.

Oh, i see,  i think it is useful, thank you, so, if not set any arguments with `C-u`,  i guess `compile` should be same as `recompile`?

**Comment by zw963** [comment]
Just for remind:  : )

 i found `(rustic-recompile)` still not working as `(rustic-compile)` do
on newest master 7c9d55b.

**Comment by brotzeit** [comment]
I fixed the original issue. `rustic-recompile` now also calls `rustic-compilation-start` so `rustic-maybe-format-before-compilation` will be called.

**Comment by zw963** [comment]
Thank you, i can confirm, it start works now!
