### ISSUE TITLE
Formatting inserts stderr of rustfmt.

### ISSUE THREAD

**Issue by Janfel** [brotzeit/rustic#153]
## Expected behavior
When formatting a source file with `rustic-format-buffer`, the stdout and stderr streams of `rustfmt` are separated to prevent any warnings or informational messages from being inserted into the formatted buffer.

## Actual behavior
The output streams are not separated and any warnings are inserted as text into the formatted buffer.

## Steps to reproduce
Create an unformatted Rust file.
  ```sh
  echo 'fn main() {foo();bar();baz();}' > test.rs
  ```
Create a `rustfmt.toml` file that causes `rustfmt` to emit warnings in the same directory.
  ```sh
  echo 'foo = "bar"' > rustfmt.toml
  ```
Format the file using `rustic-format-buffer`. The buffer now looks like this:
```rust
Warning: Unknown configuration option `foo`
fn main() {
	foo();
	bar();
	baz();
}
```

**Comment by brotzeit** [comment]
Yeah, this issue looks familiar. I thought this should be fixed with https://github.com/rust-lang/rustfmt/pull/2187

**Comment by brotzeit** [comment]
It seems they've changed the code. Did you have this issue before ? How long have you been using rustic ?

**Comment by Janfel** [comment]
I’ve just recently noticed this issue but I haven’t been using rustic for very long. I’ve looked at your PR and it seems the issues are not related. Your PR concerns printing messages on stdout while formatting stdin, whereas this issue is about rustic not splitting stdout and stderr of rustfmt properly.

I’ve used [rederr](https://github.com/poettering/rederr) to check that rustfmt is properly separating code and messages into stdout and stderr. It seems to me that the issue lies with rustic calling `make-process` without supplying the `:stderr` argument, thereby mixing stderr into stdout.

**Comment by brotzeit** [comment]
Yeah you're right. Thanks for your help!
Can you please try #159.

**Comment by Janfel** [comment]
The PR is working nicely for me. Thanks for the quick response.

**Comment by brotzeit** [comment]
I added some changes that remove the warnings from the buffer and instead prints it with `message`.
