### ISSUE TITLE
hangs during rustfmt when saving

### ISSUE THREAD

**Issue by antifuchs** [brotzeit/rustic#17]
I'm just trying out rustic, and it feels really cool! Unfortunately, I'm running into a weird problem: When I save a rust file with `rustic-format-on-save` set to `t`, emacs hangs. I used toggle-debug-on-quit, used `C-x C-s`, waited a bit and then hit `C-g`; I got this backtrace:

```
Debugger entered--Lisp error: (quit)
  rustic-before-save-hook()
  run-hooks(before-save-hook)
  basic-save-buffer(t)
  save-buffer(1)
  funcall-interactively(save-buffer 1)
  call-interactively(save-buffer nil nil)
  command-execute(save-buffer)
```

I suspect this is an interaction with something else on the `before-save-hook`, so here's what's on there:

`(eglot--signal-textDocument/willSave rustic-before-save-hook t)`

I set `rustic-rls-pkg` to `eglot`, could that be related?

**Comment by antifuchs** [comment]
(Update: I tried setting `rustic-rls-pkg` to `lsp-mode`, installed lsp-mode and restarted emacs; saving still hangs).

**Comment by brotzeit** [comment]
Did you try this with a minimal config ? I mean only rustic + eglot/lsp-mode.

**Comment by brotzeit** [comment]
@antifuchs I made some changes and hopefully it works now. If not, please open another issue. Thanks for the bug report.
