### ISSUE TITLE
Investigate possibility to automatically set rustic-flycheck-clippy-params according to active toolchain

### ISSUE THREAD

**Issue by brotzeit** [brotzeit/rustic#171]
I guess the easiest way would be to use `shell-command-to-string` to parse the output of `rustup show`.

**Comment by brotzeit** [comment]
@gagbo if you have any other ideas...

**Comment by gagbo** [comment]
I don't know if rustup overrides the correct `rustc` version when changing toolchain, but if it does I guess that parsing `rustc --version` is the only way indeed

**Comment by brotzeit** [comment]
Should be working.

**Comment by brotzeit** [comment]
> I don't know if rustup overrides the correct rustc version when changing toolchain, but if it does I guess that parsing rustc --version is the only way indeed

I totally forgot to read this again. If it doesn't work with rustup for some situations please open an issue.
