### ISSUE TITLE
When run rustic-cargo-build/run,  if main.rs exist syntax error,  cursor always skip to beginning of buffer.

### ISSUE THREAD

**Issue by zw963** [brotzeit/rustic#172]
## What i expected

When run `quit-window`, cursor should go back to original position, as it did for `rustic-recompile`.

thank you.

**Comment by zw963** [comment]
Sorry, i found i can't reproduce this issue today,  let me close it first, and enable if i can reproduce again.

Thank you.

**Comment by zw963** [comment]
I reproduce it again.

for reproduce reason, i upload my `main.rs` here.

https://raw.githubusercontent.com/zw963/zw963.github.io/master/files/main.rs

When my cursor is on line 36, then run `rustic-cargo-run`, cursor skip to beginning of buffer.

thank you.

**Comment by samhedin** [comment]
My cursor doesn't jump into the compile window at all, but that might be because of my setup. A question though - the code you posted does not compile, does working code or non-working code change the behavior?

**Comment by zw963** [comment]
@samhedin , Yes, you are right, this issue only happen on some syntax error happen on main.rs,
because this, i upload my code here.

![image](https://user-images.githubusercontent.com/549126/96713067-9e9bc280-13d2-11eb-8534-348e34cc7eab.png)

> My cursor doesn't jump into the compile window at all,

Yes, if not jump into the compile window, the cursor should jump to beginning of buffer immediately.

**Comment by brotzeit** [comment]
Sorry I can't reproduce this.

I place my cursor on line 36 in your code, run rustic-cargo-run, switch to compilation buffer and quit the compilation buffer.

I don't notice anything happening.

**Comment by zw963** [comment]
@brotzeit , can you please try use following three 3 config to reproduce?

### update lsp-mode, lsp-ui, rustic-mode, company-mode to use newest master.

### Use only following config + emacs 27.1, i can always reproduce this issue.

rustic: http://dpaste.com/GR37X6948
lsp-mode: http://dpaste.com/FYSWWTJUE
company: http://dpaste.com/CWVW2AKAZ

BTW: in fact, cursor never will be skip to compilation buffer if not config to use 
shackle package, it just skip cursor to beginning of buffer immediately when run
`rustic-cargo-run` as only above config.

**Comment by zw963** [comment]
Any idea? i just want to know, if i describe my issue clearly in  my previous comment. thank you.

**Comment by samhedin** [comment]
I sat down to take another look at this, but the pastes are gone. Could you re-upload them? :)

**Comment by zw963** [comment]
Thank you. @samhedin 

main.rs (You can see a syntax error on line 39:26, this is the prerequisite which cause this issue.)

https://raw.githubusercontent.com/zw963/zw963.github.io/master/files/main.rs

rustic config:
http://dpaste.com/AN3TVC74M

lsp-mode config:

http://dpaste.com/94XSKP4YE

company config (maybe not related, but anyway, provided it)
http://dpaste.com/AE77WEXEM

**Comment by zw963** [comment]
@samhedin , any idea?

**Comment by samhedin** [comment]
Will try tomorrow!

**Comment by samhedin** [comment]
On a fresh emacs install with only lsp-mode and rustic installed, with this in init.el (the configs you sent for lsp-mode and rustic) https://pastebin.com/raw/gjVHQupE I get almost the same error as you are talking about. Running `rustic-cargo-build` does not switch the cursor to the `*rustfmt*` window, but it does send the cursor to the top of the document. I see how this is frustrating behavior. I am very busy at the moment though so I can't look into it.

**Comment by zw963** [comment]
> On a fresh emacs install with only lsp-mode and rustic installed, with this in init.el (the configs you sent for lsp-mode and rustic) https://pastebin.com/raw/gjVHQupE I get almost the same error as you are talking about. Running `rustic-cargo-build` does not switch the cursor to the `*rustfmt*` window, but it does send the cursor to the top of the document. I see how this is frustrating behavior, but can't commit to doing anything about it atm.

Thank you for reproduce,  @brotzeit , if you have time, please try it too, thank you.

**Comment by thor314** [comment]
Having same issue. On calling `rustic-format-buffer` with a syntax error, cursor jumps to compilation buffer, and moves cursor in the rust file to somewhere near the top.

**Comment by brotzeit** [comment]
Is this also the case for `rustic-format-file` ?

**Comment by zw963** [comment]
> Is this also the case for `rustic-format-file` ?

I tested just now, it don't work too, but, `rustic-format-file` skip to another unexpected place instead of beginning of buffer.

**Comment by thor314** [comment]
@brotzeit - `rustic-format-file` reproduces the error, point jumps to other buffer, with the message `<file>.rs changed on disk; really edit the buffer? (y...)`

**Comment by zw963** [comment]
@brotzeit , i tested, `rust-format-buffer` and `rust-format-file` seems like works, but when run `rustic-cargo-run`, still same.

Thanks.

**Comment by zw963** [comment]
Hi, @brotzeit , i switched to use rust-mode + lsp, all features works quite well for now.

This issue can't be reproduce when use rust-mode instead of rustic-mode, so
this bug was not so necessory for me anyway if it hard to fix.

i will keep this issue open, if you done this, i will very happy for test it.

Thank you.

**Comment by thor314** [comment]
@zw963, I ultimately turned off `rust(ic)?-format-on-save`, which appears to have been my source of issue.

**Comment by zw963** [comment]
> @zw963, I ultimately turned off `rust(ic)?-format-on-save`, which appears to have been my source of issue.

I think i never enable this for my config since this issue was created, so, i don't think so.

**Comment by brotzeit** [comment]
@zw963 ok I was finally able to reproduce(no idea why it didn't work before).

It seems the issue is `run-hook-with-args-until-failure` in `rustic-compilation-start`. Not all cargo commands use this wrapper function. We have to call  `save-excursion` and `save-window-excursion`.

Sorry that it took so long. Wasn't that hard to find out.

**Comment by zw963** [comment]
I confirm today, it works for me now.

thank you very much!
