### ISSUE TITLE
How to use semver in org-babel crate definition?

### ISSUE THREAD

**Issue by 0atman** [brotzeit/rustic#176]
I can't seem use the `time` crate's current version in an Babel block:

```rust
#+begin_src rust :crates '((time . 0.2.22))
// cargo-deps: time
extern crate time;
fn main() {
    println!("{}", time::now().rfc822z());
}
#+end_src
```

`Wrong type argument: symbolp, "time"`

**Comment by 0atman** [comment]
I can confirm that the example works for me:

```rust
#+BEGIN_SRC rust :crates '((regex . 0.2))
extern crate regex;

use regex::Regex;

fn main() {
    let re = Regex::new(r"^\d{4}-\d{2}-\d{2}$").unwrap();
    println!("{:?}", re.is_match("2014-01-01"));
}
#+END_SRC

#+RESULTS:
: true
```

**Comment by 0atman** [comment]
The difference between the two seems, to me, to be the float version number for `regex`, and the semver for `time`?

**Comment by 0atman** [comment]
I THINK that this can never work with semver crates, because it runs `number-to-string`, which expects an int or float: https://github.com/brotzeit/rustic/blob/master/rustic-babel.el#L220

**Comment by brotzeit** [comment]
Yeah, I supposed this was the case. I guess we have change the version number to be a string.

**Comment by 0atman** [comment]
@brotzeit could it be as simple as https://github.com/brotzeit/rustic/pull/180 ? :grin: 

Full disclosure, this is the first elisp I've written!
