### ISSUE TITLE
lsp-mode as optional depenndency

### ISSUE THREAD

**Issue by vxcamiloxv** [brotzeit/rustic#178]
I'm using rustic-mode with `'eglot`, but rustic install by default `lsp-mode` and with `(setq rustic-lsp-client 'eglot)` is `lsp-mode` is not require, so I think would be great if it can be optional like eglot, for example for `rustic-doc-mode`

**Comment by brotzeit** [comment]
So if you set `(setq rustic-lsp-client 'eglot)` you don't have to install `lsp-mode` right ?

**Comment by vxcamiloxv** [comment]
yes, but not things like `rustic-doc-mode`, that show a message about require lsp-mode instaleld

**Comment by brotzeit** [comment]
Sorry I didn't get what you mean. @samhedin added this feature and currently it's only working with lsp-mode. I don't know if that's feasible with eglot.

**Comment by samhedin** [comment]
I've been looking around in the eglot source code for another PR, and clearly, I need to git gud at elisp/cl-lib before I promise to add eglot support to rustdoc. I would like to do it though.

**Comment by samhedin** [comment]
About a year ago I made an attempt to make it work with eglot, but the authors of eglot weren't huge fans of how I was using the package so I dropped that attempt. So for now it'll stay LSP-only.

**Comment by brotzeit** [comment]
I'll take a look. Can you point me to the pull request you opened for eglot ?

**Comment by samhedin** [comment]
> I'll take a look. Can you point me to the pull request you opened for eglot ?

Turns out my memory was flawed. I was thinking of this: https://github.com/brotzeit/rustic/pull/177 , which is different. Eglot support should therefore still be possible. We're looking for the request `textDocument/hover` which is used in `rustic-doc--thing-at-point`.

**Comment by samhedin** [comment]
Work on this here: https://github.com/brotzeit/rustic/pull/363

**Comment by brotzeit** [comment]
merged.
