### ISSUE TITLE
cargo-edit missing

### ISSUE THREAD

**Issue by Jake-Moss** [brotzeit/rustic#185]
Running `M-x rustic-cargo-add` prompts me to install `cargo-edit`, cargo-edit is already installed and functioning as it should from a terminal. After choosing to install it, it complains that its already installed and to force an install if I really want to.

Rerunning `M-x rustic-cargo-add` always results in the prompt that `cargo-edit` is not installed, a force install does not help.

I am using `emacs-pgtk-native-comp` from aur with Doom emacs with the `(rust +lsp)` `:lang` flag on `5.8.18-1-MANJARO`. I have tried `doom env` and `doom build`

```
$ rustc -V
rustc 1.47.0 (18bf6b4f0 2020-10-07)
$ rustup -V
rustup 1.22.1 (2020-07-08)
$ cargo install --list
cargo-edit v0.7.0:
    cargo-add
    cargo-rm
    cargo-upgrade
```

**Comment by samhedin** [comment]
My laptop is running a similar setup - Arch with `emacs-pgtk-native-comp` and Doom and it works. Even if you did run `doom env`, can you confirm that emacs can see `cargo edit` properly?

**Comment by Jake-Moss** [comment]
Running `:!cargo add time` workings as it should so I think emacs can see `cargo-edit`

**Comment by Jake-Moss** [comment]
I thought I should note that I can no longer reproduce this, it appears it may have been a quirk of my system

**Comment by brotzeit** [comment]
Thanks for the update.

**Comment by afidegnum** [comment]
i'm using vanilla emacs and facing the same thing. how can it be fixed? 
```
Cargo-edit missing. Install ? (y or n) y
cargo install cargo-edit: finished.
Cargo-edit missing. Install ? (y or n) n [2 times
```

**Comment by brotzeit** [comment]
@afidegnum did you try https://github.com/purcell/exec-path-from-shell ?

**Comment by afidegnum** [comment]
I had it installed but not used it yet. from the normal terminal, I don't have any problem, it signal an existing crate or force to override.
