### ISSUE TITLE
rustic-doc--thing-at-point: Symbol’s function definition is void: lsp:hover-contents

### ISSUE THREAD

**Issue by rhdxmr** [brotzeit/rustic#186]
The symbol `lsp:hover-contents` does not exist, so `rustic-doc-search` failed.

What package should I install to solve this problem?

**Comment by samhedin** [comment]
At the moment `rustic-doc` requires lsp-mode. I hope to add eglot support shortly. And come to think of it, I believe both of those could be made optional.
But for now, lsp-mode is required

**Comment by brotzeit** [comment]
#178
