### ISSUE TITLE
Doctest syntax highlighting and run test

### ISSUE THREAD

**Issue by jedbrown** [brotzeit/rustic#187]
It was recently pointed out to me that VS Code (with rust-analyzer) has syntax highlighting for doctests (inside the comment) and a "Run Doctests" feature (`rustic-cargo-current-test` doesn't currently recognize doctests).

![image](https://user-images.githubusercontent.com/3303/99732488-d010b800-2a7c-11eb-8e6d-8131be9a7d41.png)

**Comment by brotzeit** [comment]
Would be nice to have this feature.

**Comment by brotzeit** [comment]
I was told this feature is almost ready.

You can activate the highlighting with `(setq lsp-enable-semantic-highlighting)` and it will be able to run the doctests when https://github.com/emacs-lsp/lsp-mode/pull/2299/ was merged. Afterwards we can modifiy `rustic-cargo-current-test` to also detect doctests.

**Comment by nbfalcon** [comment]
@brotzeit my PR doesn't implement doctests, but allows clicking `references` lenses.

**Comment by nbfalcon** [comment]
We already have `Run Doctest` in LSP-mode.

**Comment by jedbrown** [comment]
@nbfalcon How does one use it? I don't see any mention grepping the source tree.

**Comment by nbfalcon** [comment]
Then a compilation buffer will open with the correct cargo command.

**Comment by nbfalcon** [comment]
You can enable `lsp-lens-mode` for all buffers automatically by `setq`-ing `lsp-lens-enable` to `t` before loading `lsp-mode` or by adding `lsp-lens-mode` to `lsp-configure-hook` after loading the package.

**Comment by jedbrown** [comment]
That's wonderful, thanks. As for a keyinding to run the current doctest, is `lsp-rust-analyzer-run` the right approach? It allows selection and has the current doctest in the list, but the first entry is the last doctest run, not the current one.

**Comment by nbfalcon** [comment]
@jedbrown `lsp-avy-lens` is an `avy` interface to `lsp-lens`. Have you ever used `avy`, e.g. with `ace-window`? It is a type of narrowing selection and works as follows: all windows fade out, and highlighted letters appear. You can type one of them, after which others will appear, etc and you continue this until you type the last letter. Then whatever action you want (switch windows, run a lens) will run.

`lsp-rust-analyzer-run` indeed prefixes the selection with the last action run. If that is good enough for you, you can use it. You can make an issue on the `lsp-mode` repo so we can add a `lsp-rust-analyzer-run-doctest` command.

You may want to ask such questions on [our gitter](https://gitter.im/emacs-lsp/lsp-mode), where you are more likely to get a response.

**Comment by jedbrown** [comment]
Thanks, I fixed a keymap conflict and see how it works now. This is enough for me so I'll close this issue. If anyone else comes to this thread, the following yields behavior similar to VS Code.
```elisp
(setq lsp-enable-semantic-highlighting t
      lsp-lens-enable t)
```
