### ISSUE TITLE
Saving multibyte characters garbled

### ISSUE THREAD

**Issue by ncaq** [brotzeit/rustic#19]
# problem

~~~rust
fn main() {
    println!("Pokémon");
    println!("こんにちは,世界");
}
~~~

↓ save

~~~rust
fn main() {
    println!("PokÃ©mon");
    println!("ããã«ã¡ã¯,ä¸ç");
}
~~~

# My rustic config

~~~
;; -*- lexical-binding: t -*-

(require 'lsp-mode)
(require 'lsp-rust)
(require 'rustic)

(add-to-list 'auto-mode-alist '("\\.rs$" . rustic-mode))
~~~

**Comment by ncaq** [comment]
I set `rustic-format-on-save` to nil.
Then garbled did not happen.

**Comment by ncaq** [comment]
I do rustic-format-buffer, and garbled.

**Comment by brotzeit** [comment]
Thanks for the bug report. Please try the latest commit and tell me if it works.

**Comment by brotzeit** [comment]
Btw, you shouldn't need `(require 'lsp-rust)` and `(add-to-list 'auto-mode-alist '("\\.rs$" . rustic-mode))`.

**Comment by ncaq** [comment]
I decided to use bad know-how for the moment.

~~~elisp
(defun rustic-format-buffer ()
  (interactive)
  (rust-format-buffer))
~~~

**Comment by brotzeit** [comment]
AFAIK rust-mode has the same problem. But I pushed a commit a few minutes ago that seems to solve the problem.

**Comment by ncaq** [comment]
> AFAIK rust-mode has the same problem. But I pushed a commit a few minutes ago that seems to solve the problem.

OK!
I checked to solve!
very very thanks!

> Btw, you shouldn't need (require 'lsp-rust) and (add-to-list 'auto-mode-alist '("\\.rs$" . rustic-mode)).

If it does not come, dialogue comes out every time and it is annoying but it makes it another issue
