### ISSUE TITLE
issue with multiple-cursors

### ISSUE THREAD

**Issue by bbigras** [brotzeit/rustic#190]
I have this issue even if I disable all my packages except multiple-cursors and rustic.

![Peek 20-11-2020 14-09](https://user-images.githubusercontent.com/24027/100117596-e3e95f00-2e6c-11eb-848b-2bd482b2cf3b.gif)

Any ideas?

GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.23, cairo version 1.16.0)
rustic                         20201113.2056

**Comment by brotzeit** [comment]
Which multiple-cursors are you using ? I've tried it with `mc/mark-next-like-this` and can't reproduce it.

**Comment by bbigras** [comment]
I was using `mc/mark-next-like-this`. I'll try to reproduce it again.

**Comment by brotzeit** [comment]
I think I've seen similar issues with mc in the past, but I don't think it's related to rust. Sometimes mc behaves a little weird.

rustic now depends on rust-mode and I'm sure if this was related to rustic, rust-mode code(it was duplicated in rustic before) is the reason and not rustic functionality.

If anybody encounters mc problems again, please open an issue at rust-mode. Thanks for the bug report.
