### ISSUE TITLE
After rustic-cargo-build/run succssful, and switch to new compilation buffer,  this buffer is writable, and can be edit.

### ISSUE THREAD

**Issue by zw963** [brotzeit/rustic#194]
### run it with `rustic-cargo-run`, we can see outout result is successful.

![image](https://user-images.githubusercontent.com/549126/100588172-7fc31100-332c-11eb-95b1-60e51ac2825b.png)

### Try input somethings try to quit current buffer and close window, e.g.  q,  get following.
![image](https://user-images.githubusercontent.com/549126/100588283-a41eed80-332c-11eb-974e-f6cf5549b9b1.png)

## expected.

this compilation buffer should be a readonly buffer, and should permit user binding `q` to `quit-window` as it does like `rustic-recompile`

Thank you.

**Comment by wannestas** [comment]
This was actually a fix to a previous bug, changed last week. If your program expects input, it's sort of tedious to enable comint mode and disable read-only mode every time your program asks for input. That's why it was changed to this.

**Comment by brotzeit** [comment]
@zw963 thanks for opening the issue, but as @wannestas mentioned users want to send input to the process without running an additional command and I can totally understand it. If you prefer running a command before entering your input you can define a function that calls 'cargo run'.

```elisp
(defun my-cargo-run ()
  (interactive)
  (call-interactively 'rustic-compile "cargo run"))
```

**Comment by zw963** [comment]
Thanks for explain

**Comment by zw963** [comment]
Do we consider add a new function as old fashion `rustic-cargo-run` function? we can keep this new function as default.

Or add a optional args bfor this?

Anyway, for me, in most of my case, i don't input anythings, jus want to see the running result in compilation buffer, and quit immedately.  IMO, if we need input somethings, in most case, run it on the terminal is the better way.

**Comment by brotzeit** [comment]
Hmmm, I'm not sure what's the best solution to cover both needs. Want to come up with a pull request that contains something that fits your needs ?

**Comment by zw963** [comment]
> Hmmm, I'm not sure what's the best solution to cover both needs. Want to come up with a pull request that contains something that fits your needs ?

At least, should we only writable if build successful? anyway, build failed with writable was not so useful.

**Comment by brotzeit** [comment]
I don't know how we can detect when build has finished and run has started.
