### ISSUE TITLE
next-error jumps to second error/warning if there is no output preceding the first

### ISSUE THREAD

**Issue by birkenfeld** [brotzeit/rustic#197]
In some cases, `cargo` will not output anything like "Compiling crate" (I don't know why...).  Then, the first error/warning is apparently considered "visited" by `next-error` it jumps immediately to the second error.  With `previous-error` you can still go back to it.

(In normal compilation-mode `compilation-start` inserts the timestamp and the command at the beginning, so this never happens.  Why is `compilation-start` not used by rustic-compile?)

**Comment by brotzeit** [comment]
Hi birkenfeld. There were several reasons, but I wrote this almost as long ago as it was that I talked to you. I'd have to think about it.

**Comment by birkenfeld** [comment]
No worry, I just switched modes again and wanted to share my immediate findings. It is of course not a problem for now to use normal compilation mode again, but I'm already missing the nice colors :)

**Comment by brotzeit** [comment]
Thanks I appreciate that ;)

You could try to motivate @mookid to merge https://github.com/rust-lang/rust-mode/pull/397 by tesging his branch =)

**Comment by brotzeit** [comment]
Is this fixed now ?

**Comment by birkenfeld** [comment]
Which commit could have fixed it?

**Comment by brotzeit** [comment]
Wrong issue, sorry.

**Comment by brotzeit** [comment]
-> #355
