### ISSUE TITLE
rust-mode overrides auto-mode-alist rather than rustic-mode

### ISSUE THREAD

**Issue by ncaq** [brotzeit/rustic#20]
> Btw, you shouldn't need (require 'lsp-rust) and (add-to-list 'auto-mode-alist '("\\.rs$" . rustic-mode)).
>
> https://github.com/brotzeit/rustic/issues/19#issuecomment-447262678

But, I environment, I need

~~~elisp
(add-to-list 'auto-mode-alist '("\\.rs$" . rustic-mode))
~~~

Because, rust-mode override.

I can not delete rust-mode,
Because, `rust-mode Required by: racer-20181213.225, lsp-rust-20180305.1308`.

**Comment by brotzeit** [comment]
rustic removes rust-mode from `auto-mode-alist`. I guess you require rust-mode after rustic. I will mention this in the readme.

**Comment by brotzeit** [comment]
I have to make a patch. rust-mode gets removed in rustic mode and that can't work. I will fix it.

**Comment by ncaq** [comment]
I write workaround.

~~~elisp
(cl-delete-if (lambda (element) (equal (cdr element) 'rust-mode)) auto-mode-alist)
(add-to-list 'auto-mode-alist '("\\.rs$" . rustic-mode))
~~~

**Comment by brotzeit** [comment]
I added an installation section in the readme.

**Comment by zoechi** [comment]
Looks like I run into this or a similar issue. I couldn't find this section in the readme though.

**Comment by brotzeit** [comment]
rustic is not a fork anymore so this shouldn't be necessary.

**Comment by brotzeit** [comment]
If you can't fix it please open a new issue with your config.
