### ISSUE TITLE
If there is no (require 'lsp-mode), the install dialog will appear each time

### ISSUE THREAD

**Issue by ncaq** [brotzeit/rustic#21]
> Btw, you shouldn't need (require 'lsp-rust) and (add-to-list 'auto-mode-alist '("\\.rs$" . rustic-mode)).
>
> https://github.com/brotzeit/rustic/issues/19#issuecomment-447262678

But, I need `(require 'lsp-mode)`.

Without this, even if you install lsp-mode you will be installing it every time.

~~~
lsp-mode not found. Install it ? (y or n) y
Saving file /home/ncaq/.emacs.d/custom.el...
Wrote /home/ncaq/.emacs.d/undo-tree/.!home!ncaq!.emacs.d!custom.el.~undo-tree~
Wrote /home/ncaq/.emacs.d/custom.el [2 times]
Saving file /home/ncaq/.emacs.d/custom.el...
Wrote /home/ncaq/.emacs.d/undo-tree/.!home!ncaq!.emacs.d!custom.el.~undo-tree~
Wrote /home/ncaq/.emacs.d/custom.el [2 times]
‘lsp-mode’ is already installed
File mode specification error: (void-function lsp-rust-enable)
~~~

**Comment by brotzeit** [comment]
Yeah, I know. I had problems to require the packages dynamically. I will give it another try.

**Comment by brotzeit** [comment]
This should work now. Please confirm.

**Comment by ncaq** [comment]
OK, I use eglot.
