### ISSUE TITLE
Including specific features from crate in org-babel

### ISSUE THREAD

**Issue by DouglasGray** [brotzeit/rustic#210]
Hello! Firstly thank you for the awesome work, this package has made writing and dealing with rust in emacs a breeze.

I was wondering if it's possible to specify particular features I want from a crate when using `rustic` with `org-babel`? For example, if I want to use `serde` and `#[derive(Serialize)]` with `org-babel` and `rustic` I can't seem to currently, since I need to include `features = ["derive"]` in the `Cargo.toml` entry for `serde`. 

Supposing this functionality isn't available at the moment, would you be open to a PR to add it? Admittedly my elisp knowledge is almost non-existent, however this might be a good intro.

**Comment by brotzeit** [comment]
Hey, sure I would accept a PR. However I'm currently not sure how difficult it is. Since we want to have the contents of the Cargo.toml file in a different babel block we have to link the blocks somehow, so when the main block is executed the contents of the corresponding Cargo.toml block are inserted automatically.

When you have a solution for that the rest will be easy.

**Comment by brotzeit** [comment]
It should be similar to the logic that is needed for #122.

**Comment by DouglasGray** [comment]
Hey, thanks for the swift reply. It seems I have underestimated the task considerably :) Sadly I don't think I'm in a position right now to tackle this properly with my current elisp knowledge.

However I think I may have found a hack for my use case. I was messing around with function `rustic-babel-cargo-toml` which takes the `alist` specifying the crate to also accept a pair of `(version (features ..))` in the `cdr` position, for example:
```
#+begin_src rustic :crates '((serde "1.0" ("derive")) (serde_json . "1.0"))
...	
#+end_src
```
or 
```
#+begin_src rustic :crates '((tokio "1.0" ("rt-multi-thread" "macros")))
...
#+end_src
```
and got it working, it merely replaces the `crate_name = version_num` string that is generated and added to `Cargo.toml` with `crate_name = {"version" = version_num, "features = [feature_1, feature_2, ..]}`. Would a PR with this be of any use?

**Comment by brotzeit** [comment]
I didn't think of it before but for this case it would also be possible and easier to add a parameter `:features` that can be passed like `:crates`. 

The solution I mentioned would be more difficult to implement, but it would allow using all possible options in Cargo.toml.

You would only have to extend `rustic-babel-cargo-toml` with similiar logic that we use for dependencies(`:crates`). If you want to give it a try I can help you with it.

**Comment by DouglasGray** [comment]
That sounds like a better approach, happy to have a go!

**Comment by DouglasGray** [comment]
Regarding how it's specified, are you thinking something like the below?
```
#+begin_src rustic :crates '((serde . "1.0") (serde_json . "1.0")) :features '((serde . "derive"))
...
#+end_src
```
```
#+begin_src rustic :crates '((tokio "1.0")) :features '((tokio . ("rt-multi-thread" "macros")))
...
#+end_src
```
If so, what shall we do in the case of crates that aren't specified in `:crates` but do appear in `:features`? Possible options are set version to `*` or call `user-error`?

**Comment by brotzeit** [comment]
Hmmm I think `user-error` is too much in this case. But you can implement it how you want. If necessary we can always add a `defcustom`.

**Comment by DouglasGray** [comment]
I've cooked something preliminary up [here](https://github.com/brotzeit/rustic/compare/master...DouglasGray:feature/iss-210/rustic-babel-add-crate-features) which appears to work on a first pass. A couple examples below:

```
#+begin_src rustic :crates '((serde . 1.0) (serde_json . "1.0")) :features '((serde . "derive"))
...
#+end_src
```
or
```
#+begin_src rustic :crates '((tokio . 1.0)) :features '((tokio . ("rt-multi-thread" "time")))
...
#+end_src
```
I also tried running `make test` to check I haven't broken anything however I get the below error which also appears in a clean download of the repo:
```
Compiling rustic-common.el

In toplevel form:
rustic-common.el:69:1:Error: Wrong type argument: listp, val
make: *** [Makefile:61: rustic-common.elc] Error 1
```

**Comment by brotzeit** [comment]
Yeah I remember `make test` is broken. Does it work with `cask exec ert-runner` instead ?

**Comment by DouglasGray** [comment]
I believe so. Results from my fork:
```
Ran 245 tests in 23.140 seconds
1 expected failures
```
Results from a fresh download of the repo:
```
Ran 245 tests in 26.283 seconds
1 expected failures
```

**Comment by DouglasGray** [comment]
Sorry for the delay on this! I added a couple tests and opened a [PR](https://github.com/brotzeit/rustic/pull/220)
