### ISSUE TITLE
Integrate `cargo-process` in rustic

### ISSUE THREAD

**Issue by rakanalh** [brotzeit/rustic#225]
Hello,

In my configs, i am replacing compilation-related commands provided by rustic with `cargo-process`. I think the buffer provides better navigation of the errors rather than a simple display of the errors. Shortcuts like `[[` and `]]` enable going through the errors where pressing `ENTER` on one of the errors takes you to the file on which the error was detected.

```
(after! rustic
  (map! :localleader
        :map rustic-mode-map
        :prefix "b"
        :desc "cargo build"
        "c" #'cargo-process-check)

  (map! :localleader
        :map rustic-mode-map
        :prefix "b"
        :desc "cargo build"
        "b" #'cargo-process-build)

  (map! :localleader
        :map rustic-mode-map
        :prefix "b"
        :desc "cargo build"
        "r" #'cargo-process-run)
  (map! :localleader
        :map rustic-mode-map
        :prefix "b"
        :desc "cargo check w/ tests"
        "t" (cmd! (cargo-process--start "Check Tests" "check --tests"))))
```

Is this something that can be natively done by rustic-mode?

**Comment by brotzeit** [comment]
Sorry I didn't get to this issue earlier.

>  I think the buffer provides better navigation of the errors rather than a simple display of the errors. Shortcuts like [[ and ]] enable going through the errors where pressing ENTER on one of the errors takes you to the file on which the error was detected.

rustic makes use of a compilation mode, meaning that you can use its commands that allow you to navigate as you mention it.
This is documented in the very first line of the [compilation section](https://github.com/brotzeit/rustic#compilation).

If this isn't working for you or you are missing some features, please open a new issue. Thanks for the feature request!

**Comment by brotzeit** [comment]
Maybe the docs should be improved ?

**Comment by brotzeit** [comment]
d6f086d1d21da2b54a0f305b0283d2abb9252a41
