### ISSUE TITLE
When opening complex projects, Rust Analyzer crashes: "starting exited with status exit. Do you want to restart it?"

### ISSUE THREAD

**Issue by thor314** [brotzeit/rustic#226]
When opening a complex project like https://github.com/near/nearcore, Rust Analyzer will crash with the minibuffer message "starting exited with status exit. Do you want to restart it?"

If I accept, RA crashes immediately again with the same message.

If I do not accept, I just fall back to not having an LSP, whatever rustic-mode provides without Rust Analyzer.

**Comment by samhedin** [comment]
Is the behavior different when running regular rust-mode? This seems more related to LSP or RA than rustic, but I could of course be mistaken.

**Comment by brotzeit** [comment]
@samhedin you're right, the probability that this is related to rustic is very low.

**Comment by thor314** [comment]
Thanks, will see if I can find out more up the stream.
