### ISSUE TITLE
rustic-doc-setup fails silently on macOS: nproc not present

### ISSUE THREAD

**Issue by antifuchs** [brotzeit/rustic#227]
I am just trying out rustic-mode, and would love to use its convenient doc lookup; unfortunately on macOS (without a `coreutils` installation), there is no `nproc` program, which makes `~/.local/bin/rustic-doc-convert.sh` fail:

```
:;    /Users/asf/.local/bin/rustic-doc-convert.sh  std
Generating org files in: /Users/asf/.local/share/emacs/rustic-doc/std
/Users/asf/.local/bin/rustic-doc-convert.sh: line 51: nproc: command not found
error: The argument '--threads <num>' requires a value but none was supplied

USAGE:
    fd [FLAGS/OPTIONS] [<pattern>] [<path>...]

For more information try --help
:;    echo $?
1
```

What's even more concerning though, is that running `M-x rustic-doc-setup RET` succeeds. Here's an excerpt from my `*Messages*` buffer:

```
Contacting host: raw.githubusercontent.com:443
Wrote /Users/asf/.local/bin/rustic-doc-convert.sh
Wrote /Users/asf/.local/bin/rustic-doc-filter.lua
Setup is converting the standard library
Finished converting docs for std
```

I'm going to install coreutils to get the `nproc` program (would be good to have anyway), but it would be really useful if the setup function could error if that conversion tool exits non-0, instead of pretending that everything is alright.

**Comment by samhedin** [comment]
> it would be really useful if the setup function could error if that conversion tool exits non-0, instead of pretending that everything is alright.
Completely agreed. In addition, maybe we could add a more macos native function call there instead of relying on the user installing nproc. `sysctl -n hw.logicalcpu` is apparently one way to do it, but I can't try it out as I don't have access to a mac.

**Comment by antifuchs** [comment]
`sysctl -n hw.logicalcpu` on my 8-core macbook returns 16, same as `nproc` from coreutils does - that would be a viable solution!

**Comment by samhedin** [comment]
@antifuchs could you give it a try and confirm that everything works on macos? If so we can close this

**Comment by samhedin** [comment]
Closing for now :/)
