### ISSUE TITLE
File mode specification error: (void-function lsp-rust-enable)

### ISSUE THREAD

**Issue by ncaq** [brotzeit/rustic#23]
`rustic-setup-rls` cause

~~~
File mode specification error: (void-function lsp-rust-enable)
~~~

I write work around.

~~~elisp
;; lsp-rust-enableが消滅したのでバッドノウハウとしてダミーの関数を定義する
(unless (fboundp 'lsp-rust-enable)
  (defun lsp-rust-enable ()
    ()))
~~~

This problem seems to be caused by upgrading lsp-mode package.

* [void-function lsp-rust-enable · Issue #37 · emacs-lsp/lsp-rust](https://github.com/emacs-lsp/lsp-rust/issues/37)

**Comment by brotzeit** [comment]
Yeah I encountered this issue yesterday myself. Thanks for the hint, I will fix this.

**Comment by otavio** [comment]
I also faced this issue. The workaround did work.

**Comment by ncaq** [comment]
This can also be avoided by using eglot instead of lsp-mode.
What's more like making eglot dedicated and making lsp-mode deprecated?

**Comment by brotzeit** [comment]
If you use the solution from above, the lsp server won't get started. You can also set `rustic-rls-pkg` to `nil` if you don't want to use `eglot`. That's the same result.

**Comment by otavio** [comment]
> If you use the solution from above, the lsp process won't get started. You can also set `rustic-rls-pkg` to `nil` if you don't want to use `eglot`. That's the same result.

I got it working here. https://github.com/otavio/.emacs.d/blob/master/lisp/init-rust.el

**Comment by brotzeit** [comment]
Nice. A pull request with the fix would be very welcome =)

**Comment by brotzeit** [comment]
@otavio I copied the fix from your config. Thanks!
