### ISSUE TITLE
Running rustic-cargo-fmt disables rustic-mode

### ISSUE THREAD

**Issue by creese** [brotzeit/rustic#234]
After formatting a buffer with `C-c C-c C-f`, the buffer is formatted and saved (expected) but also leaves rustic-mode and enters rust-mode (unexpected). Before I can use rust-analyzer, I must re-enable rustic-mode via `M-x rustic-mode`. If I use `(setq rustic-format-on-save t)`, I also have to re-enable rustic-mode every time the buffer is saved.

I using Emacs 27.1.

**Comment by brotzeit** [comment]
Thanks for the bug report. Do you get the same result when you turn off lsp-mode ?

**Comment by creese** [comment]
I don't know what that is. Here are the relevant lines:

```
(require 'rustic)
(add-hook 'rustic-mode-hook (lambda () (setq indent-tabs-mode nil)))
(add-hook 'rustic-mode-hook 'display-fill-column-indicator-mode)
(add-hook 'rustic-mode-hook #'rainbow-delimiters-mode)
(add-hook 'rustic-mode-hook #'smartparens-mode)
(setq rustic-format-on-save t)
```

**Comment by brotzeit** [comment]
> Before I can use rust-analyzer

How do you use rust-analyzer ? lsp-mode is a package that serves as a client.

> but also leaves rustic-mode and enters rust-mode 

You shouldn't load rust-mode when you want to use rustic-mode and vice versa, for several reasons.

**Comment by creese** [comment]
> How do you use rust-analyzer ? lsp-mode is a package that serves as a client.

lsp-mode is enabled. I see it under `describe-mode`.

> You shouldn't load rust-mode when you want to use rustic-mode and vice versa, for several reasons.

I'm not loading rust-mode. Could this be built into Emacs now?

**Comment by brotzeit** [comment]
Do you use a starter package like spacemacs ?

**Comment by creese** [comment]
It looks like rust-mode was still installed. After I removed it, the problem away.

**Comment by brotzeit** [comment]
Ok :+1:
