### ISSUE TITLE
the `-Z` flag is only accepted on the nightly channel of Cargo

### ISSUE THREAD

**Issue by tleydxdy** [brotzeit/rustic#235]
```
Suspicious state from syntax checker rustic-clippy: Flycheck checker rustic-clippy returned 101, but its output contained no errors: error: the `-Z` flag is only accepted on the nightly channel of Cargo, but this is the `stable` channel
See https://doc.rust-lang.org/book/appendix-07-nightly-rust.html for more information about Rust release channels.

Try installing a more recent version of rustic-clippy, and please open a bug report if the issue persists in the latest release.  Thanks!
```

I'm not using LSP or anything. since I saw https://github.com/brotzeit/rustic/issues/112

**Comment by brotzeit** [comment]
Hi, this is a message of cargo. Unless I misunderstand you, you can't do that. However lsp-mode should also work with clippy now(https://emacs-lsp.github.io/lsp-mode/page/lsp-rust/#lsp-rust-clippy-preference).

**Comment by tleydxdy** [comment]
I'm using Doom emacs, and enabled the rust module there. This is what happens when I tries to edit my rust projects, I think this happens because of the changes in https://github.com/brotzeit/rustic/issues/112 and my emacs trying to check for code errors.

**Comment by brotzeit** [comment]
FTR the default config is for nightly. If you want to use stable put this in your config `(setq rustic-flycheck-clippy-params "--message-format=json")` (https://github.com/brotzeit/rustic#flycheck)

@tleydxdy I think you used stable but you didn't adjust `rustic-flycheck-clippy-params`. In case I'm wrong and anybody still encounters this issue, please reopen the issue or open a new one. Thanks for the bug report.
