### ISSUE TITLE
Can't format remote buffers 

### ISSUE THREAD

**Issue by dangirsh** [brotzeit/rustic#241]
If I open a TRAMP buffer to a remote `.rs` file, `rustic-format-file` fails with an error like:

```
Error: file `/ssh:<remote>:<path>/src/main.rs` does not exist
```

`rustic-format-buffer` works fine. 

Unsure why, but `rustic-before-save-hook` uses `rustic-format-file` instead of `rustic-format-buffer`. This leads to many annoying popups on remote buffers, since I have formatting configured to run on each save.

A quick solution is to replace `rustic-format-file`with `rustic-format-buffer` in `rustic-before-save-hook`.

**Comment by brotzeit** [comment]
> Unsure why, but rustic-before-save-hook uses rustic-format-file instead of rustic-format-buffer

The reason is that `rustic-format-buffer` doesn't always work reliable in terms of buffer position and users prefered `rustic-format-file` in the past.

I actually never used rust on a remote host. Does this work for you ?

```diff
modified   rustic.el
@@ -1192,11 +1192,13 @@ This handles multi-line comments with a * prefix on each line."
 (defun rustic-before-save-hook ()
   "Don't throw error if rustfmt isn't installed, as it makes saving impossible."
   (when (and (rustic-format-on-save-p) (not (rustic-compilation-process-live t)))
-    (condition-case nil
-        (progn
-          (rustic-format-file)
-          (sit-for 0.1))
-      (error nil))))
+    (if (file-remote-p (buffer-file-name))
+        (rustic-format-buffer)
+      (condition-case nil
+          (progn
+            (rustic-format-file)
+            (sit-for 0.1))
+        (error nil)))))
        (error nil)))))
```

**Comment by dangirsh** [comment]
This works. Thanks for the fast fix!

**Comment by brotzeit** [comment]
Let's leave this open until we have merged it.

**Comment by brotzeit** [comment]
Should be working now.
