### ISSUE TITLE
Fixup README for LSP over TRAMP

### ISSUE THREAD

**Issue by dangirsh** [brotzeit/rustic#243]
I struggled to get LSP to connect to a remote `rust-analyzer` server by following the README.

I think in #217, the config relied on a matching directory structure between the local and remote machines (hinted in [this comment](https://github.com/brotzeit/rustic/issues/217#issuecomment-763572913)).

Here's a configuration that works for me. The difference is in `:new-connection`: I use `lsp-tramp-connection` instead of `lsp-stdio-connection`. I also assume "rust-analyzer" is in the remote path, instead of trying to find it (this could be improved). The previous version was (incorrectly) finding the path on the local machine.

```
(with-eval-after-load "lsp-rust"
  (lsp-register-client
   (make-lsp-client
    :new-connection (lsp-tramp-connection "rust-analyzer")
    :remote? t
    :major-modes '(rust-mode rustic-mode)
    :initialization-options 'lsp-rust-analyzer--make-init-options
    :notification-handlers (ht<-alist lsp-rust-notification-handlers)
    :action-handlers (ht ("rust-analyzer.runSingle" #'lsp-rust--analyzer-run-single))
    :library-folders-fn (lambda (_workspace) lsp-rust-library-directories)
    :after-open-fn (lambda ()
                     (when lsp-rust-analyzer-server-display-inlay-hints
                       (lsp-rust-analyzer-inlay-hints-mode)))
    :ignore-messages nil
    :server-id 'rust-analyzer-remote)))
```

Happy to make a PR to update the README if this looks alright.

Thank you for this package! Now that the remote dev setup is working, I think it's the most effective Rust development environment available.

**Comment by brotzeit** [comment]
> Thank you for this package! Now that the remote dev setup is working, I think it's the most effective Rust development environment available.

Thanks but there's not much competition, I'm also the only maintainer of rust-mode that replies every now and then ;)

The issue with rustic is unfortunately that it still has some quirks, so rust-mode is IMO still a good alternative if you want things to "just work".

Regarding rust-analyzer, it might be the best solution to add this in the docs of lsp-mode and link it from the rustic readme. Ideally, users can find all the relevant lsp-mode docs in its own repository, so rust-mode users disadvantaged.
