### ISSUE TITLE
`rustic-popup` window behvaior

### ISSUE THREAD

**Issue by masonium** [brotzeit/rustic#250]
Is there a way to configure `rustic-popup` to close the window that it creates once a command is run? The default behavior that I experience is that the window is left open and the buffer switches to a recent one, so my frame is quickly overrun with small windows unless I explicitly delete them.

**Comment by brotzeit** [comment]
Sorry for the late reply. We can add a `defcustom` to let the user decide whether to close the window or not.

> and the buffer switches to a recent one

After you run a command this happens ? That shouldn't be the case.

**Comment by masonium** [comment]
It seems to happen only when running a command that isn't completely successful (i.e. running `clippy` or `compile` when there are still errors.) When running `fmt`, for instance, the popup stays in place and quitting via `q` kills the window as expected.

**Comment by brotzeit** [comment]
Should be working now. I added a note to the readme. A short feedback would be nice(if it's working). Thanks for the feature request.
