### ISSUE TITLE
Rustic does not recognize Rust hex notation

### ISSUE THREAD

**Issue by amyipdev** [brotzeit/rustic#252]
![image](https://user-images.githubusercontent.com/46307646/119235362-00e2b000-bae7-11eb-923b-c774cfc4be18.png)

**Comment by brotzeit** [comment]
Sorry for the late reply. It seems nobody added highlighting yet.

**Comment by brotzeit** [comment]
This is now a rust-mode issue since rustic is no longer a fork of rust-mode and requires it as dependency.

**Comment by brotzeit** [comment]
This can be done with [tree-sitter](https://github.com/rust-lang/rust-mode#highlighting-with-tree-sitter)
