### ISSUE TITLE
uses obsolete project-root function

### ISSUE THREAD

**Issue by iitalics** [brotzeit/rustic#256]
When I run `rustic-cargo-build` (`C-c C-c C-b`) I get the following error:
```
rustic-project-buffer-list: Symbol’s function definition is void: project-root
```
this appears to be because `project-root` is considered obsolete:
https://github.com/emacs-mirror/emacs/blob/master/lisp/progmodes/project.el#L235

I noticed that [this commit](https://github.com/brotzeit/rustic/commit/61c37a8dd0ea561ba2641f656cb9a51963af58ad) removed this dependency even though this function is still in use.

How do I get `rustic-cargo-build` to work again?

**Comment by brotzeit** [comment]
Yeah this is annoying. I hope we get this fixed in https://github.com/brotzeit/rustic/pull/258/files#diff-f221a9ba4b35068873ca12e7f89930d3a21a417baa72bca1196f40e421440fe5R11

**Comment by brotzeit** [comment]
I added a function that checks the emacs version and makes use of the correct function name.

**Comment by iitalics** [comment]
sweet, thanks!
