### ISSUE TITLE
Fix error parsing

### ISSUE THREAD

**Issue by brotzeit** [brotzeit/rustic#26]
It still doesn't work reliably. If anybody knows a solution for this compile.el issue, a PR would be very appreciated (even better would be a fix in compile.el itself but a workaround in rustic would also be nice).

**Comment by Dushistov** [comment]
Looks related to rust-lang/rust-mode#308

The original emacs bug multi line errors + compile.el is from 2016: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=25133

**Comment by brotzeit** [comment]
Yeah, I forgot to add those links. Thanks! It would be great if anybody could confirm this still doesn't work. I added a call to `compilation--ensure-parse`, but I don't think this helps. But this was some time ago, so I actually have no idea...

**Comment by Dushistov** [comment]
>  It would be great if anybody could confirm this still doesn't work. 

I reported bug against rust-mode several days ago.

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=36001

One from emacs devs even created unit test for this bug during investigation:

https://debbugs.gnu.org/cgi/bugreport.cgi?att=1;filename=bug-36001-reproducer.el;bug=36001;msg=22

**Comment by kellpossible** [comment]
I'm getting problems where flycheck is showing out-of-date errors. Could this be related? Also is there any way to force a refresh?

**Comment by brotzeit** [comment]
I'm pretty sure that it's not related. The flycheck checkers either run their own process or use the output of the lsp server.

**Comment by brotzeit** [comment]
Which checker do you use ?

**Comment by mbuczko** [comment]
hey,
I also see the issue that @kellpossible's mentioned. Please have a look at the gif:

![Kapture 2020-05-31 at 22 52 04](https://user-images.githubusercontent.com/586537/83362468-c80b7180-a391-11ea-8e37-1491117a422e.gif)

I'm not sure if it is related to rustic though. Anyway, just wanted to say huge thanks for your work, by the way :)

**Comment by kellpossible** [comment]
@brotzeit flycheck I think? Or it is provided by lsp-rust... I'm not sure yet how all the pieces fit together in emacs for Rust.

**Comment by brotzeit** [comment]
Yeah, this issue looks familiar. It's definitely not related to rustic. I'm pretty sure this is a flycheck issue. Is this the lsp-mode checker or did you activate the rustic checker ?

**Comment by mbuczko** [comment]
I'm not sure how to verify that, but I'd say it's lsp-mode checker (I did not add `rustic-clippy` checker yet). Looking at how it behaves, seems like the error shown by flycheck always refers to "previously saved" state. This is why on animation above the problem disappears when I save correct state again.

**Comment by brotzeit** [comment]
-> #355
