### ISSUE TITLE
Loading from melpa fails: bind-key-20210210.1609.el: Bad Request

### ISSUE THREAD

**Issue by worikgh** [brotzeit/rustic#260]
`package-install-from-archive: https://melpa.org/packages/bind-key-20210210.1609.el: Bad Request`
Is in the *Messages* buffer

```
$ cat /etc/issue
Raspbian GNU/Linux 10
```

`GNU Emacs 26.1 (build 2, arm-unknown-linux-gnueabihf, GTK+ Version 3.24.5) of 2021-02-07, modified by Debian`

Starting:
```
package-activated-list is a variable defined in ‘package.el’.
Its value is
(f hideshow-org ht dash markdown-mode pkg-info epl s spinner xterm-color)
```

Run this:
```
package-activated-list is a variable defined in ‘package.el’.
Its value is
(f hideshow-org ht dash markdown-mode pkg-info epl s spinner xterm-color)
```

The results (from *Messages*)
```
Loading /home/patch/.emacs...
Importing package-keyring.gpg...done
Contacting host: elpa.gnu.org:443
Failed to download ‘gnu’ archive.
Contacting host: melpa.org:443
Package refresh done
Failed to download ‘melpa’ archive.
Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations [2 times]
Contacting host: melpa.org:443
package-install-from-archive: https://melpa.org/packages/bind-key-20210210.1609.el: Bad Request
```

Is there any more information I should supply?

**Comment by worikgh** [comment]
Looking into `biind-key` in `list-packages`

```
bind-key is an available package.

     Status: Available from melpa -- [Install]
    Archive: melpa
    Version: 20210210.1609
     Commit: a7422fb8ab1baee19adb2717b5b47b9c3812a84c
    Summary: A simple way to manage personal keybindings
   Homepage: https://github.com/jwiegley/use-package
   Keywords: [keys] [keybinding] [config] [dotemacs]
```

**Comment by brotzeit** [comment]
What does your package.el related config look like ? Btw. this is not really related to this package ;)

**Comment by worikgh** [comment]
```
(require 'package)
(setq package-archives
      '(("GNU ELPA"     . "https://elpa.gnu.org/packages/")
        ("MELPA Stable" . "https://stable.melpa.org/packages/")
        ("MELPA"        . "https://melpa.org/packages/"))
      package-archive-priorities
      '(("MELPA Stable" . 10)
        ("GNU ELPA"     . 5)
        ("MELPA"        . 0)))
(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(eval-when-compile
  (require 'use-package))


(require 'use-package)
```

**Comment by worikgh** [comment]
`use-packkage` is not listed in output of command `package-list-packages`

Nor is any package mentioning `rust`

**Comment by worikgh** [comment]
On further investigation:
Teh command `package-refresh-contents` gives error: 
```
Contacting host: elpa.gnu.org:80 [2 times]
Failed to download ‘MELPA Stable’ archive.
Contacting host: melpa.org:80
Failed to download ‘MELPA’ archive.
```
I switched to `http:` makes no difference.
I am going over to the `melpa` page to report the issue there.

I am using a fresh install (as in purged the old install and deleted all local `emacs` configuration)

**Comment by worikgh** [comment]
MELPA were rude to me.  

But I think this is a bug in emacs 26.1

**Comment by brotzeit** [comment]
> MELPA were rude to me.

We all have a bad day every now and then. The guy who answered you is a really nice guy that puts lots of time and energy into the emacs ecosystem.

Maintainers sometimes also reply a little frustrated because there are many users that are asking questions which are not related to the project.

r/emacs can always be used to ask questions, if you are not sure where to ask.
