### ISSUE TITLE
How can I change rust target dir of rust-analyzer?

### ISSUE THREAD

**Issue by rhdxmr** [brotzeit/rustic#264]
I want to change a target directory of `cargo check` that is executed by `rust-analyzer.`

There is a variable `lsp-rust-target-dir` but changing this variable does not affect the target directory when using `rustic` + `rust-analyzer.`

How can I change `rust-analyzer` to execute `cargo check` with `--target-dir` arguments when I am using `rustic`?

**Comment by brotzeit** [comment]
`lsp-rust-target-dir` is only used for rls.

I suppose you are using `rustic-cargo-check` ? The command uses the directory in the buffer's `default-directory`.

Or do you use a lsp-mode command ?

**Comment by rhdxmr** [comment]
I don't execute `rustic-cargo-check` directly.

I figured out that `cargo check` command is executed whenever I save emacs buffers with rustic mode.
And I realized that the `cargo check` is executed by `rust-analyzer`.

I guess that `rust-analyzer` server process communicates with emacs via LSP protocol. And `rust-analyzer` monitors files and when the files change it executes `cargo check`.

I am wondering whether I can change the target directory of `cargo check` that is executed by `rust-analyzer`.
I assume that if I can pass some initialization parameters to `rust-analyzer`, I can change its behavior maybe.

**Comment by brotzeit** [comment]
I would take a look at these lsp-mode options:

```elisp
(defcustom lsp-rust-analyzer-cargo-watch-command "check"
  "Cargo watch command."
  :type 'string
  :group 'lsp-rust
  :package-version '(lsp-mode . "6.2.2"))

(defcustom lsp-rust-analyzer-cargo-watch-args []
  "Cargo watch args."
  :type 'lsp-string-vector
  :group 'lsp-rust
  :package-version '(lsp-mode . "6.2.2"))

(defcustom lsp-rust-analyzer-cargo-override-command []
  "Advanced option, fully override the command rust-analyzer uses for checking.
The command should include `--message=format=json` or similar option."
  :type 'lsp-string-vector
  :group 'lsp-rust
  :package-version '(lsp-mode . "6.2.2"))
```

**Comment by brotzeit** [comment]
@rhdxmr it would be great if you could add an example to the lsp-mode wiki if it works.

**Comment by rhdxmr** [comment]
@brotzeit As you suggested `lsp-rust-analyzer-cargo-watch-args` solved the problem.
I set this variable like below
```elisp
(custom-set-variables
;; ...omitted...
 '(lsp-rust-analyzer-cargo-watch-args ["--target-dir" "target/analysis"]))
```

> @rhdxmr it would be great if you could add an example to the lsp-mode wiki if it works.

Ok I will do that

Thanks,
