### ISSUE TITLE
emacs 27 rustic-clippy errors even with nightly toolchain installed

### ISSUE THREAD

**Issue by amitavaghosh1** [brotzeit/rustic#268]
❯ rustup toolchain list
stable-x86_64-apple-darwin (default)
stable-x86_64-unknown-linux-gnu
nightly-x86_64-apple-darwin

❯ rustup component add --toolchain nightly clippy
```
Suspicious state from syntax checker rustic-clippy: Flycheck checker rustic-clippy returned 101, but its output contained no errors: error: the `-Z` flag is only accepted on the nightly channel of Cargo, but this is the `stable` channel
See https://doc.rust-lang.org/book/appendix-07-nightly-rust.html for more information about Rust release channels.

Try installing a more recent version of rustic-clippy, and please open a bug report if the issue persists in the latest release.  Thanks!
user-error: Minibuffer window is not active
```

The stable version works all right with `(setq rustic-flycheck-clippy-params "--message-format=json")`

am I missing anything?

**Comment by brotzeit** [comment]
Is nightly really the active toolchain when you run `rustup show` ?

**Comment by QuantDimension** [comment]
Same error here, yes, rustup show points to nightly rustup

**Comment by mbuczko** [comment]
similiar situation here but in a slight different variation - error message on stable, no error on nightly. in both cases flycheck doesn't discover any errors though.

**Comment by brotzeit** [comment]
If not please reopen...

**Comment by mbuczko** [comment]
works perfectly. thanks for a patch!
