### ISSUE TITLE
Feature Request: hide warnings when running tests

### ISSUE THREAD

**Issue by renatoathaydes** [brotzeit/rustic#271]
Hi @brotzeit , amazing job with the `rustic` mode, I've been using it for a few days and it's great, everything works together quite well, much better than most other LSP modes!

Just wanted to create a feature request: when I run my tests, because I have lots of unfinished code (in the middle of a redesign) I can't see test results easily as they get drowned by warnings.

When I run tests, I would prefer to have an option to hide those. I can run Clippy later to see warnings and hints.

What do you think? Could this be a rustic feature, or better to customize the cargo options somehow to  omit warnings temporarily?

Thanks for the great work!

**Comment by renatoathaydes** [comment]
Maybe even something that "follows" the end of the test output buffer could help me actually... switching to the other buffer just to bring it to the bottom to see results is a bit annoying.

**Comment by brotzeit** [comment]
> everything works together quite well, much better than most other LSP modes!

Thanks, but lsp related features are provided by lsp-mode.

> What do you think? Could this be a rustic feature, or better to customize the cargo options somehow to omit warnings temporarily?

Yeah I've also thought about it. I think it would make sense to introduce a customization option that allows the user to add parameters to 'cargo test'. And we could add the default to omit warnings.

**Comment by brotzeit** [comment]
I don't want to make this a default because it seems when changing env vars the whole crate will be rebuild. However it's now possible to activate it with `(setq rustic-cargo-test-disable-warnings t)`.
