### ISSUE TITLE
Make cargo-test-rerun use previously executed tests if not configured otherwise

### ISSUE THREAD

**Issue by renatoathaydes** [brotzeit/rustic#273]
> rustic-cargo-test-rerun rerun 'cargo test' with arguments stored in rustic-test-arguments

Wouldn't it be better to re-run the test previously executed? Maybe that would require parsing the arguments to see if it restricts which tests should run, but when I try a command called `test-rerun` I would expect it would re-run whatever I ran before?!

**Comment by brotzeit** [comment]
`rustic-test-arguments` was also considered to be used for additional arguments besides the tests. When that code was added there wasn't a function like `rustic-cargo-current-test`. That's what you want, a function that reruns the test that was ran by this function, right ? When you are calling `rustic-cargo-test` with `C-u` and enter the name of a test, that's what's called when you call `rustic-cargo-test-rerun`.

But maybe it makes sense to add a function `rustic-cargo-current-test-rerun`.

**Comment by brotzeit** [comment]
> However, my other PR has been laying there for some time now idle, would be nice if you could show that you value contributions and either tell me if there's anything else I need to change (I changed what you'd asked by the way) or please merge it.

Sorry, I'm a little lazy during the summer. You can always ping me to wake me up ;)
I'm currently trying to catch up on rustic and emacs-ng.

If you are really motivated and want to help me motivate myself, I can add you as a collaborator. There's also @samhedin who helped me a lot but I think he's currently busy with school =)

**Comment by renatoathaydes** [comment]
I am happy to make small PRs for now. If I end up using rustic a lot in the future, we'll see. Thanks for the offer.

**Comment by brotzeit** [comment]
`rustic-cargo-current-test` now sets `rustic-test-arguments` so `rustic-cargo-test-rerun` makes use of the test.
