### ISSUE TITLE
Awesome work

### ISSUE THREAD

**Issue by worikgh** [brotzeit/rustic#275]
I am loving rustic

Like all things rust  it is a bossy beast.  How I used to hate getting bossed around by software, back in the day.  Silly me!  It is a real help and a fantastic piece of work.

Congratulations!

**Comment by brotzeit** [comment]
Thanks for the feedback, but don't forget that most functionality comes from lsp clients ;)

When I started writing the package there were several rust related packages and the intention was to "include" the functionality in one package to make it easier for users. And most of the code is from rust-mode and other users. So thanks to everybody who contributed.

But we generally have the problem that there are too few maintainers. Reviewing pull requests can be hard work, especially when you want to ensure that there won't be any regressions. I hope that contributors understand that it can take some time to merge pull requests and fix issues. But I'm always glad when I can add collaborators to a project...

**Comment by worikgh** [comment]
After thirty years using Emacs I have no Emacs Lisp.  Shame on me.

**Comment by brotzeit** [comment]
Thanks for the feedback!
