### ISSUE TITLE
Arguments passed for 'cargo run' can be confused with cargo's options.

### ISSUE THREAD

**Issue by JerryHue** [brotzeit/rustic#276]
When I was testing a program by running it with `cargo run`, I used the `rustic-cargo-run` command interactively. I passed the argument `-v` to test my option parsing step, and I noticed my program was not behaving correctly. I tried it with `-h`, as well, and it showed me the help section for `cargo run` in the **`rustic-compilation`** buffer, which helped me to understand what the error is.

The `rustic-cargo-run` function does not add the [`--` to separate the program arguments from the `cargo` arguments](https://doc.rust-lang.org/cargo/commands/cargo-run.html). I believe this error may happen, too, if the function is called with `M-x`.

**Comment by brotzeit** [comment]
I added the '--' to the initial prompt string. Thanks for the feature request!
