### ISSUE TITLE
It needs to be saved twice for error checking

### ISSUE THREAD

**Issue by ncaq** [brotzeit/rustic#28]
I guess it is because I am running rustfmt.
The error check will not work unless you save it once and save it again.

It is troublesome and troublesome.

My setting.

[ncaq/.emacs.d: Emacsの設定ディレクトリ](https://github.com/ncaq/.emacs.d)

~~~elisp
;; -*- lexical-binding: t -*-

;; rust-modeで開かれる時があるのでrustic-modeを末尾に追加し直す
(cl-delete-if (lambda (element) (equal (cdr element) 'rust-mode)) auto-mode-alist)
(cl-delete-if (lambda (element) (equal (cdr element) 'rustic-mode)) auto-mode-alist)
(add-to-list 'auto-mode-alist '("\\.rs$" . rustic-mode))

;; 本当にwithout switchしているわけではなく前のウィンドウにフォーカスを戻すだけ
(defun pop-to-buffer-without-switch (buffer-or-name &optional action norecord)
  (pop-to-buffer buffer-or-name action norecord)
  (other-window -1)
  )

;; エラーポップアップにフォーカスを移さない
(custom-set-variables '(rustic-format-display-method 'pop-to-buffer-without-switch))
~~~

**Comment by brotzeit** [comment]
Does it work when you set `rust-format-on-save` to nil ?

**Comment by brotzeit** [comment]
Yeah I know this issue, but it always disappeared again. I have to take a look at this.
Does this problem always occur or is it temporary ?

**Comment by ncaq** [comment]
I will neither get up nor get up.
If it is severe you must save about 5 times or flycheck will not move.
Perhaps I think that the timing of preservation and rustfmt is shifted ...

**Comment by brotzeit** [comment]
So if I understand correctly we have to trigger flycheck somehow after rustfmt ?

**Comment by ncaq** [comment]
I think that flycheck is not directly related to this matter.
Because, when this bug is activated,
`save-buffer` can be executed many times without editing anything,
The file is saved.

Perhaps.

1. Save the buffer
2. rustfmt rewrites the buffer
3. The buffer is rewritten and the file can be saved
4. Save the buffer

I think that it is becoming an infinite loop of.

**Comment by brotzeit** [comment]
Can you please check the latest changes.

**Comment by ncaq** [comment]
great great great!
I checked to fix.
Think you.
