### ISSUE TITLE
missing support to define root for rust code in mono-repo setup with multi-member workspace

### ISSUE THREAD

**Issue by mikonieminen** [brotzeit/rustic#280]
Currently rustic-mode fails to find project root correctly when having workspace with multiple members (packages). Additionally, if you have uni-repo project where rust code is located in a subfolder, there is no easy way to hint rustic for the rust code root.

There's already some discussion regarding this issue in [doom](https://github.com/hlissner/doom-emacs/issues/4070) and with help of @mplanchard I managed to get even my uni-repo case work, where the root for rust code is under `myunirepo/rust` by creating `myunirepo/.dir-locals.el` with following content:
```lisp
((nil . ()) ;; no settings for all modes
 (rustic-mode ;; for rustic mode
  ;; ensure the buffer workspace is always set to the project root to work around
  ;; brotzeit/rustic#179 and brotzeit/rustic#236
  . ((eval . (advice-add 'rustic-buffer-workspace :override (lambda (&optional ignored) (format "%srust/" (projectile-project-root))))))))
```

With this snippet in `.dir-locals.el` the projectile correctly discovers the root for the full project while `rustic-mode` passes correct project root to LSP and only one instance of `rust-analyzer` is started.

It would be nice if there is a safe variable for `rustic-mode` that could be used for defining where the project root is in this kind of scenario.

**Comment by brotzeit** [comment]
We could add an option that allows the user to choose a function that returns a path with the root the user wants. And defaults to `project-root`.
