### ISSUE TITLE
Feature Request: Integrate a variable explorer

### ISSUE THREAD

**Issue by afidegnum** [brotzeit/rustic#283]
I was trying to implement but i'm still at a loss. 
A possibility fo a variable/method explorer where a variable can have a small buffer displaying valid methods, transformation this variable can obtain, which will help in the development and minimize the try-and-error process.

**Comment by Patryk27** [comment]
@afidegnum that's what Ctrl + Space does, isn't it?

**Comment by afidegnum** [comment]
I couldn't find my way out with _dap-mode._ what helped is I changed from _rust-analyzer_ to _rls_ which helped a bit `Ctrl+Space `by default is bound to mark and highlighting

**Comment by brotzeit** [comment]
>  A possibility fo a variable/method explorer where a variable can have a small buffer displaying valid methods, transformation this variable can obtain

I'm pretty sure I've seen this, but I can't find it. I think lsp-mode + lsp-ui has this feature.

**Comment by brotzeit** [comment]
I think `lsp-find-implementation` and maybe also `lsp-find-references` are what you are looking for.

If there's still something missing, you should open an issue at the repo of your prefered lsp client. The functionality you are talking about is something that is provided by lsp these days so rustic is the wrong place. Except for improving existing lsp features, however in most cases even this should better be added to lsp clients so rust-mode users can also use it.

p.s. you should really use rust-analyzer ;)
