### ISSUE TITLE
Sending input in Cargo run mode errors with wrong-type-argument

### ISSUE THREAD

**Issue by jun0** [brotzeit/rustic#295]
When I send input to an inferior process in Cargo run mode, upon hitting RET, I get `(wrong-type-argument number-or-marker-p nil)` in `comint-add-to-input-history`.  It seems that `comint-send-input` doesn't work unless comint variables are initialized by a call to the `comint-mode` function.  Additionally, `rustic-cargo-run-mode` calls `kill-all-local-variables`, which undoes all initializations in `comint-mode`, so we somehow need to arrange that initialization to happen after `rustic-cargo-run-mode`.

Unfortunately, I don't know enough about Elisp to know how to make that happen, but here's a workaround for the time being.  It sets up an around-advice that initializes `comint-mode` before `rustic-cargo-run-mode`, then saves and restores comint-related local variables during the initialization of `rustic-cargo-run-mode`.

    (defun my-rustic-cargo-run-mode-comint-fix (orig-fun &rest args)
      (comint-mode)
      (let* ((comint-bindings (cl-loop
                               for (sym . val) in (buffer-local-variables)
                               if (string-prefix-p "comint-" (symbol-name sym))
                               collect (cons sym val)))
             (ret-val (apply orig-fun args)))
        (cl-loop for (sym . val) in comint-bindings
                 do (make-local-variable sym)
                    (set sym val))
        ret-val))
    (advice-add 'rustic-cargo-run-mode
                :around
                #'my-rustic-cargo-run-mode-comint-fix)

System Details:
System: macOS X Big Sur
Emacs version: GNU Emacs 27.2 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G95)) of 2021-03-28
Rustic version: rustic-20211018.1934 (pulled from melpa)

**Comment by brotzeit** [comment]
I think it makes sense to keep this open since the fix is still optional.

For anybody who is interested -> https://github.com/brotzeit/rustic#run

**Comment by brotzeit** [comment]
@psibi will add some docs on compilation-mode and comint-mode for 'cargo run'. If somebody has issues with polymode please open a new issue.

@jun0 thanks!
