### ISSUE TITLE
Support cargo clippy --fix on save, similar to rustfmt

### ISSUE THREAD

**Issue by brotzeit** [brotzeit/rustic#300]
https://github.com/rust-lang/rust-mode/issues/413

- [x] on compile
- [ ] on save

**Comment by brotzeit** [comment]
We probably also want to provide fix `'on-compile` similar to the rustfmt options in rustic.

**Comment by brotzeit** [comment]
I have troubles implementing the hook for both clippy and rustfmt. I wonder if we realy need this functionality for saving since we can't run clippy fix on a single file(or maybe I missed something). It's already possible to run the fix automatically before compilation. Any opinions ?

**Comment by samhedin** [comment]
I personally do not use on-save hooks for 3rd party tools, since I save frequently, and having a formatter shift everything in the buffer every 2 seconds is annoying. If nobody is very adamant about adding it, I'm sure it's fine without.

**Comment by brotzeit** [comment]
Same for me. I don't even use the on-compilation hooks but I think they make more sense, this way you can't forget rustfmt and clippy.
