### ISSUE TITLE
flycheck should use the output of lsp-mode

### ISSUE THREAD

**Issue by brotzeit** [brotzeit/rustic#31]
Flycheck shouldn't run an additional process, but use rls output somehow. I think flymake works that way, but I didn't take a look at it.

**Comment by gagbo** [comment]
On this subject, I can't seem to gather the errors at all when using `rust-analyzer` as the LSP server. Do you know if that's a limitation from the server, `lsp-mode`, or something we can do in `rustic` ?

**Comment by brotzeit** [comment]
This shouldn't make any difference since the flycheck checkers run cargo without lsp-mode. That's what it used to be. I have to take a look at this.

**Comment by brotzeit** [comment]
It seems lsp-ui now adds its own flycheck checker and you can view the errors found by rls with `lsp-ui-flycheck-list`. But `flycheck-list-errors` doesn't seem to access these sources. 

Can you tell me your value for `lsp-rust-clippy-preference` and check both error listing flycheck commands with rls und rust-analyzer.

For rust-analyzer clippy isn't configured yet.

**Comment by brotzeit** [comment]
Since flycheck can either start a process by itself or use the output of lsp-mode, we have to provide an option to let the user decide which source to use and document it properly so the user doesn't use multiple checkers simultaneously.

**Comment by gagbo** [comment]
Sorry I totally missed that, I'' try to get these variables this week-end

**Comment by brotzeit** [comment]
No problem. I'm just updating the status for everybody who is interested.

**Comment by brotzeit** [comment]
lsp-mode now comes with a generic flycheck checker.
