### ISSUE TITLE
auto reload rust-analyzer when Cargo.toml has changed

### ISSUE THREAD

**Issue by brotzeit** [brotzeit/rustic#322]
https://github.com/hlissner/doom-emacs/issues/5630

I think it makes more sense to add this to rustic instead of lsp-mode.

- [ ] lsp-mode
- [ ] eglot

**Comment by brotzeit** [comment]
This is actually a lsp client issue. I'll keep it open until we know it's working for both clients.

**Comment by brotzeit** [comment]
I've tested it with lsp-mode and eglot and both seem to work ? I think we should discuss this in lsp-mode/eglot, we have better chances to get some help there.

**Comment by jadestrong** [comment]
<img width="688" alt="image" src="https://user-images.githubusercontent.com/18475217/153796201-85c2ca10-29e1-4deb-a860-94bc1826c95e.png">

I tried it on Linux and Windows. Their `file-notify--library` is`inotify` and `w32notify` respectively, which can work normally, but `kqueue` is used on my Mac computer, so it still can't work normally here.

**Comment by brotzeit** [comment]
I didn't even know about this =)

Sorry, but I can't help here.
