### ISSUE TITLE
Feature Request: add option to convert `*rust-errno*` buffer markdown-view as orgmode-view

### ISSUE THREAD

**Issue by lroolle** [brotzeit/rustic#325]
![image](https://user-images.githubusercontent.com/14071051/142759737-9f5d1d8e-022a-48f9-98dc-ab89d27e1f38.png)

The `rustc --explain` errno buffer's Markdown-View is actually good enough.

By adding support to covert org-mode can be as fantastic as the doc-search like below, I think:

![image](https://user-images.githubusercontent.com/14071051/142759616-2ffb22de-5779-49f7-9dd6-6c99ffd5410e.png)

**Comment by lroolle** [comment]
By reusing some of the `rustic-doc/filter.lua` this works out easy like this:

![image](https://user-images.githubusercontent.com/14071051/142760201-60186a5e-f28d-4d13-9e59-b45552b61ec7.png)

**Comment by brotzeit** [comment]
Do you want to open a pull request ?

**Comment by lroolle** [comment]
> Do you want to open a pull request?

Yes,  assign me, I'll try in some spare time.

**Comment by brotzeit** [comment]
@lroolle should I clear the assignment ? No problem if you currently don't have the time to implement it. I'm making good progress cleaning up the issue tracker so I have to ask ;)

**Comment by lroolle** [comment]
> @lroolle should I clear the assignment ? No problem if you currently don't have the time to implement it. I'm making good progress cleaning up the issue tracker so I have to ask ;)

Sorry I forgot this, I am unable to spare some time to do this, please clear the assignment, thanks.

By the way, I found myself didn't use much of the error - explanation page, what is your ideas about this feature? I think you may close it as you like?

**Comment by brotzeit** [comment]
I actually didn't think about it yet =)

And I also don't use the error explanations.

But now that you mention it I think org-mode doesn't provide any advantage over markdown in this case. It seems to me that the explanations are rather short. I think org-mode is fantastic for rustic-doc especially when looking at large documentations.

I keep the issue open for now, maybe somebody is motivated to pick it up. Maybe I'll close it after some time.

**Comment by brotzeit** [comment]
Other opinions ?

**Comment by lroolle** [comment]
> But now that you mention it I think org-mode doesn't provide any advantage over markdown in this case. It seems to me that the explanations are rather short. I think org-mode is fantastic for rustic-doc especially when looking at large documentations.
> 
> I keep the issue open for now, maybe somebody is motivated to pick...

Agree

**Comment by brotzeit** [comment]
I've taken another look at several errors. markdown is probably enough. But if somebody still wants to implement this I don't have a problem with it. Thanks anyway.
