### ISSUE TITLE
Update rustic-doc/filter.lua

### ISSUE THREAD

**Issue by samhedin** [brotzeit/rustic#334]
There have been some updates to the html for rust documentation that have made the generated org-files look worse.
 
- [ ] Some areas have an insane amount of whitespace. This has been a constant issue but it's worse now.
The right place to fix these should be `filter.lua`.
- [X] Some items have been added to the sidebar which should be removed:
![screenshot](https://user-images.githubusercontent.com/1848063/145676765-725b10fe-ce95-49b7-96ee-af64f059da05.png)
Compare to the sidebar in https://doc.rust-lang.org/std/option/enum.Option.html

**Comment by brotzeit** [comment]
@samhedin is this issue fixed ?

**Comment by samhedin** [comment]
Yes! I intend to make some more drastic changes to the filter soon.
