### ISSUE TITLE
Add support for `cargo-lints`

### ISSUE THREAD

**Issue by appetrosyan** [brotzeit/rustic#341]
https://github.com/i1i1/cargo-lints 

Is an incredibly convenient wrapper around clippy, which allows encoding the lints used for a project in a `lints.toml` file, instead of being passed either to the global `clippy` configuration, or via command-line arguments. 

It'd be very useful if rustic mode could support the command if its installed.

**Comment by brotzeit** [comment]
Want to give it a try ? Basically it should be just adding an additional element to the command list.

Maybe add a defcustom for the default parameters.

```elisp
;;;###autoload
(defun rustic-cargo-clippy-run (&optional args)
  "Run `cargo clippy' with optional ARGS."
  (interactive)
  (let* ((command (list rustic-cargo-bin "clippy"))
         (c (append command (split-string (if args args ""))))
         (buf rustic-clippy-buffer-name)
         (proc rustic-clippy-process-name)
         (mode 'rustic-cargo-clippy-mode))
    (rustic-compilation-process-live)
    (rustic-compilation c (list :buffer buf :process proc :mode mode))))
```

I would tag this as low-hanging-fruit for anybody who is interested in implementing it.
