### ISSUE TITLE
can't make format on save work: Symbol definition is void rust-after-save-hook

### ISSUE THREAD

**Issue by vcombey** [brotzeit/rustic#343]
I'm struggling to make rustic format on save my files. I go the error:
Symbol definition is void rust-after-save-hook

My config is basic:
(use-package rustic
  :config
  (setq rustic-format-trigger 'on-save))

Mannualy M-x rustic-format-file and Mx rustic-format-buffer work fine, however.
What I'm doing wrong ?

**Comment by brotzeit** [comment]
`rust-after-save-hook` is defined in rust-mode. So this means you don't have the required rust-mode version.

I just noticed that I forgot to add a tag for the last rust-mode release. Maybe that's the reason why this wasn't updated, but I actually doubt it. How do you install rustic ? I just bumped rust-mode and the required version for rustic. Can you give it another try with master please.

**Comment by brotzeit** [comment]
I think this should be fixed. Tests are also working. Please reopen the issue if it still doesn't work.

**Comment by vcombey** [comment]
Confirming it's working by uninstalling rustic and rust-mode and reinstalling rustic
Thank you !
