### ISSUE TITLE
`rustic-cargo.el` requires the location of the cargo binary, not `rustic-compile.el`

### ISSUE THREAD

**Issue by TheBlackBeans** [brotzeit/rustic#345]
I have a setup in which there is no unique cargo binary for every project, but instead each project asks for a certain cargo binary, which is provided in the `PATH`.

In short, this means that, in a shell, for example, you can run `cargo`, but there is no way to know beforehand where the binary will be. This works well when I run `M-x rustic-compile`, due to the fact that rustic simply execute a command ([see this line](https://github.com/brotzeit/rustic/blob/d124b1638ba3df967dea870576d62588a5053d5e/rustic-compile.el#L29)), but it does not work when I run `M-x rustic-cargo-test` (for example) because then rustic uses a customizable path instead of letting the path being resolved dynamically ([see this definition](https://github.com/brotzeit/rustic/blob/d124b1638ba3df967dea870576d62588a5053d5e/rustic-cargo.el#L15-L18)).

Concretely, the former one simply calls `cargo build`, and succeeds, whereas the latter one calls `~/.cargo/bin/cargo test`, and fails, because there is no such file.

It's quite unclear to me why there are two different ways in the same project of calling cargo, and what is even more unclear to me is why one of them presumes the location of the binary. It seems to me that the correct one is to call `cargo <...>`, not `~/.cargo/bin/cargo <...>`.
Because of that, I'm not sure whether to label this as a bug, or as a feature request, but anyways it would be nice if all rustic commands worked like `rustic-compile`, resolving the command on-the-fly instead of having to customize the binary location by hand.

**Comment by brotzeit** [comment]
I recently added remote support for rustic and this only works with absolute paths. But I can understand you(we already had this issue in the past). I guess I will just add two variables, one for local one for remote.

> It's quite unclear to me why there are two different ways in the same project of calling cargo

That's because providing remote support is work in progress.

**Comment by brotzeit** [comment]
Should be working again, sorry for that. Sometimes I introduce bugs that I already fixed in the past =)

Thanks for the bug report!

**Comment by TheBlackBeans** [comment]
Indeed, rebuilt Emacs this morning and it's working like a charm.

> Thanks for the bug report!

Well, thanks for the bug fix =)
