### ISSUE TITLE
Putting garbage in `'rustic-lsp-server` selects rls

### ISSUE THREAD

**Issue by masklinn** [brotzeit/rustic#348]
When trying to configure rustic, I mistakenly put the path to rust-analyzer in `'rustic-lsp-server` instead of `'rustic-analyzer-command`. Upon reload and trying to enable LSP, it kept telling me that RLS was crashing, despite me having never requested or mentioned it. Looking at the LSP log those told me I had somehow selected RLS over rust-analyzer, at which point I went back to the config and realised I'd set the wrong variable.

I can only assume that an invalid value falls back to RLS, rather than either selecting the default (possibly with a warning) or triggering an error.

**Comment by brotzeit** [comment]
This sounds like emacs has problems with $PATH. I use `exec-path-from-shell` to fix this.

```elisp
(use-package exec-path-from-shell)
(exec-path-from-shell-initialize)
```

You can validate this by setting a path for rust-analyzer:

(setq rustic-analyzer-command '("~/.cargo/bin/rust-analyzer"))

**Comment by masklinn** [comment]
@brotzeit yes I did that afterwards so it could find cargo (and dropped the `rustic-analyzer-command` as it wasn't necessary anymore), but what I was trying to report here is that rustic behaves weirdly when  doing this:

    (setq rustic-lsp-server '("~/.cargo/bin/rust-analyzer"))

This setq is nonsense, but rather than either throw an error or keep the default (rust-analyzer) rustic decided this meant I wanted to use rls, that's what surprised me, and which I wanted to report.

Sorry if I wasn't clear.

**Comment by brotzeit** [comment]
Ok now I understand. However that's actually lsp-mode functionality. But I think today almost everybody is using rust-analyzer. And I think there are only few people who have rls installed besides rust-analyzer. I think lsp-mode throws an error if you don't have rls installed(and want to use rust-analyzer with broken config).

**Comment by masklinn** [comment]
> Ok now I understand. However that's actually lsp-mode functionality. But today almost everybody is using rust-analyzer. And I think there are only few people who have rls installed besides rust-analyzer. lsp-mode should throw an error if you don't have rls installed(and want to use rust-analyzer with broken config).

Possibly, as it happens I do have rls installed on this machine for some reason.

**Comment by brotzeit** [comment]
I just realized that I also would have expected that there should be an error if the defcustom gets a wrong value. So you are right, that's confusing. That's what `type` should do...

```elisp
(defcustom rustic-lsp-server 'rust-analyzer
  "Choose your LSP server."
  :type '(choice (const :tag "rls" rls)
                 (const :tag "rust-analyzer" rust-analyzer))
  :group 'rustic)
```

**Comment by brotzeit** [comment]
But I think that's intentionally...

**Comment by brotzeit** [comment]
So I tested this behavior again but with different packages like magit. It seems this is the default. I agree with you, but I think we shouldn't implement special functionality to make rustic behave differently than every other package. It should be changed in emacs itself, but I really think this was done intentionally.

Thanks for the bug report!
