### ISSUE TITLE
No longer loading rust-compilation buffer

### ISSUE THREAD

**Issue by marcantonio** [brotzeit/rustic#357]
Previously, `rustic-cargo-run` automatically opened a `rustic-compliation` buffer. That no longer happens. The buffer exists but it's not automatically displayed and focused.

Maybe related to https://github.com/brotzeit/rustic/pull/354?

I just upgraded to the latest version (last one was a few weeks old).

Happy to provide more info.

**Comment by brotzeit** [comment]
No that was my fault. I already expected this will have side effects but didn't test it manually. Thanks for the bug report!

**Comment by brotzeit** [comment]
I've added some tests so this won't happen again.

**Comment by marcantonio** [comment]
Thanks! Keep up the great work.

**Comment by brotzeit** [comment]
:+1:
