### ISSUE TITLE
Add custom flags to, and use better defaults for the `check`, `clippy` and `test` commands

### ISSUE THREAD

**Issue by appetrosyan** [brotzeit/rustic#360]
`cargo check`, `cargo clippy` and `cargo test` have a bunch of flags that allow you to broaden the scopes of tests. I currently still have to use the shell, because the following flags are not easy to add in. 

`--workspace` - works by default. 
`--benches` - check/lint benchmarks
`--tests` - check/lint tests
`--all-features` - compile with all features enabled. Particularly helpful, since `rust-analyzer` doesn't do a good job at showing errors in optional features. 
`--quiet` - Admittedly, just a personal preference, however, I would prefer not having to scroll down to the bottom of a buffer to see the error messages. 

Additionally, if the commands could be customised, one could also add some linker magic to use `mold` and speed up execution of the aforementioned `tests`. 

Ideally by default, since all of these commands are programmed not to fail if something is absent, the command that should be called instead of plain `cargo check` should probably be: 
```
cargo check --workspace --benches --tests --all-features
``` 
unless otherwise specified by the user. In reality only the bare minimum `cargo check` is run.

**Comment by brotzeit** [comment]
We can add options that allow changing the default arguments. However I'm not sure if we should change them by default. Let me think about it.
