### ISSUE TITLE
Print the command executed in the rustic-compilation buffer

### ISSUE THREAD

**Issue by psibi** [brotzeit/rustic#372]
Now now when we do rustic build etc, we get a new `rustic-compilation` buffer which looks like this:

```
   Compiling my-package v0.9.0
...
...
```

Instead having something like this would be better IMO:

```
  cargo build my-super-package --some-option  

   Compiling my-package v0.9.0
...
...
```

I can volunteer to implement this if others think that this isn't a bad idea. :-)

**Comment by brotzeit** [comment]
Sure, makes sense :+1: 

And thanks for volunteering ;)
