### ISSUE TITLE
Running multiple commands

### ISSUE THREAD

**Issue by marcantonio** [brotzeit/rustic#378]
I'm looking to run more than just `cargo run` when I build my project. I'd love to exec something like `cargo run -- arg1 arg2 && ./a.out`. This doesn't seem possible with `rustic-cargo-run-command` nor with rustic-run-shell-command`, I get:
```
error: Found argument '&&' which wasn't expected, or isn't valid in this context
```

Is it possible to run multiple commands in one go? If not, is this functionality you're interested in?

I'll just use a script for now.

**Comment by psibi** [comment]
You can use the universal argument to pass the additional arguments to it. It will prompt for passing the additional arguments to it when used with `C-u`.

**Comment by psibi** [comment]
Ah, I see what you mean. You want to use something like `&&`. But rustic-mode passes it to `cargo`...

**Comment by brotzeit** [comment]
So the idea is that you also want to reuse the compilation buffer ? I think that would imply a lot more work than using a new compilation buffer for the second process.

**Comment by marcantonio** [comment]
Yeah, the more I think about it, it seems not worth it. A simple shell script solves the issue. Sorry for the noise.
