### ISSUE TITLE
cargo command support

### ISSUE THREAD

**Issue by jubnzv** [brotzeit/rustic#38]
I found several [functions](https://github.com/brotzeit/rustic/blob/master/rustic-cargo.el#L310) in rustic sources related to `cargo` command calls.
What are they needed for? Some of them doesn't work, e.g. `rustic-cargo-new` will fails [here](https://github.com/brotzeit/rustic/blob/master/rustic-compile.el#L283) on `rustic-compilation-process-live`, if there is no active projectile project.

Are you planning to add cargo command wrappers? Something like [cargo.el](https://github.com/kwrooijen/cargo.el).
I could take it and work on those functions. For example, here is my [simple wrapper](https://github.com/jubnzv/rustic/commit/e01173d57b205f470af077392b5b38dd4e30ff17) around `cargo new`.

**Comment by brotzeit** [comment]
Sounds great! Just open a PR.

Out of curiosity, do you use org babel ? I rarely use `cargo new` because of org babel.

**Comment by jubnzv** [comment]
Ok, I'll make it a bit cleaner and then create PR, because for now it doesn't show command output.

> Out of curiosity, do you use org babel ? I rarely use `cargo new` because of org babel.

Oh, just try it today. It's really good for writing small code snippets while learning rust.
