### ISSUE TITLE
flycheck marks wrong line in workspace submodule

### ISSUE THREAD

**Issue by mbuczko** [brotzeit/rustic#387]
There seems to be a mismatch in what flycheck marks as an error and the really erroneous line. Interestingly, it happens in workspaces only. I prepared a trivial reproducible example [here](https://github.com/mbuczko/workspaces) which visualises the issue:

![Screenshot from 2022-02-15 23-52-29](https://user-images.githubusercontent.com/586537/154163389-626c5b96-cdbe-4d69-9ade-11bdd60fb13c.png)

I'm not sure if it's rustic or lsp, so I'm sorry in advance if this report went into a wrong bucket.

**Comment by brotzeit** [comment]
Did this work before ?

**Comment by mbuczko** [comment]
Honestly - I don't know. This is actually the first time I tried to use rustic for project with workspaces. It works perfectly for flat ("non-workspace") projects but I guess workspaces might mess with file locations and confuse rustic somehow.

**Comment by brotzeit** [comment]
I recently adjusted some code so error parsing also works with workspaces, but this issue isn't related to paths but line numbers so it's likely a different reason. And I only updated stuff related to compilation and not flycheck+lsp. I'll take a look.

**Comment by brotzeit** [comment]
I can't reproduce it using your example project. Are you using lsp-mode or eglot ? I just noticed that you use doom. Did you update rustic ? doom seems to use a commit that's almost 6 months old.

**Comment by brotzeit** [comment]
But I actually doubt that's the reason...

**Comment by mbuczko** [comment]
I'm using lsp-mode and the newest rustic package available on elpa (right now it's `20220216.1155`). also: `rustc 1.60.0-nightly (09cb29c64 2022-02-15)` and rust-analyzer compiled today straight from master.

**Comment by mbuczko** [comment]
if there is anything I could debug - let me know. I just need some starting point :)

**Comment by mbuczko** [comment]
this is my actual set up:
```elisp
(setq rustic-lsp-server (quote rust-analyzer)
        rustic-lsp-client (quote lsp-mode)
        rustic-lsp-format t
        rustic-format-trigger nil)

(after! rustic-flycheck
    (add-to-list 'flycheck-checkers 'rustic-clippy)))
```

**Comment by brotzeit** [comment]
`(add-to-list 'flycheck-checkers 'rustic-clippy)` is only for users that don't use lsp. Out of curiosity, why are you using `quote` ?

**Comment by mbuczko** [comment]
> why are you using quote?

I think it's just a leftover after my initial attempts to configure rustic.
So here is the current config:
```elisp
(setq 
  rustic-lsp-server 'rust-analyzer
  rustic-lsp-client 'lsp-mode
  rustic-lsp-format t
  rustic-format-trigger nil)
```
I also got rid of the hook with `add-to-list ...`. But now, all the flycheck decorations disappeared 🤔

**Comment by mbuczko** [comment]
Ok, I think I found the culprit. Looks like `rustic-mode` was not registered in `lsp` flychecker. Calling `(lsp-flycheck-add-mode 'rustic-mode)` solved the problem. I'm not sure though why I need to call it explicitly...

Anyway, seems it's all caused by my poor configuration - sorry for the noise.

**Comment by brotzeit** [comment]
So it seems we have to issues here. The non-lsp checker marks the wrong line and the lsp-mode checker doesn't work out of the box.

**Comment by mbuczko** [comment]
> The non-lsp checker is fixed 

works great, thank you!

**Comment by brotzeit** [comment]
I tested it again and it now seems to also work with lsp-mode, don't know what the problem was. If it's still doesn't work for anybody, leave a comment.
