### ISSUE TITLE
Spaces in `rustic-rustfmt-args` string are not divided into separate arguments

### ISSUE THREAD

**Issue by nickbp** [brotzeit/rustic#389]
As a workaround for `rustfmt`'s insistence on [ignoring the Cargo.toml `edition` that everything else honors](https://github.com/rust-lang/rustfmt/issues/4454), I've settled on just passing it `--edition 2021` all the time, much more preferable than leaving `rustfmt.toml` files scattered everywhere.

However, I found that the `rustic-rustfmt-args` setting doesn't work with spaces. Specifically, I noticed is that this works:
```
(setq rustic-rustfmt-args "--edition=2021")
```

But this doesn't:
```
(setq rustic-rustfmt-args "--edition 2021")
```
The latter version results in the following error in a `*rustfmt*` buffer:
```
Unrecognized option: 'edition 2021'
```

This error can be duplicated by hand in a manual `rustfmt` invocation at the commandline:
```
$ rustfmt "--edition 2021" example.rs 
Unrecognized option: 'edition 2021'
```

My assumption is that multi-word `rustic-rustfmt-args` aren't being broken down into separate arguments. Per above, the workaround for a single argument is to avoid spaces by using the `--x=y` format. However this may not be an option for someone that has multiple separate arguments that they'd like to pass (like say `--color=never --edition=2021`?).

**Comment by brotzeit** [comment]
Thanks for the bug report. Should be a simple fix.

**Comment by brotzeit** [comment]
Should be working now.
