### ISSUE TITLE
Eglot with rustic

### ISSUE THREAD

**Issue by KaranAhlawat** [brotzeit/rustic#395]
Even after setting `rustic-lsp-client` to `eglot` with `(setq rustic-lsp-client 'eglot)`, enabling `rustic-mode` inside a rust buffer errors out saying it cannot find a file or directory by the name of `lsp-mode`. Is this the intended behavior, that we still need to have lsp-mode installed even if we use eglot?

System Information:
OS: Fedora 35
Emacs: 27.2

Thanks in advance, and willing it help out in whatever capacity I can.

**Comment by samhedin** [comment]
My guess is that this will solve it: https://github.com/brotzeit/rustic/pull/363
I'll get it done.

**Comment by KaranAhlawat** [comment]
Thanks a lot for your work! I'll just stick with rust-mode till that is merged.

**Comment by brotzeit** [comment]
@samhedin do you know what's the issue, it's not about rustic-doc right. I thought I know what's the issue but I can't reproduce it.

@KaranAhlawat can you please show me the config you are using for rustic and eglot(in the order you are actually using).

**Comment by samhedin** [comment]
> @samhedin do you know what's the issue, it's not about rustic-doc right. I thought I know what's the issue but I can't reproduce it.

I assumed it was https://github.com/brotzeit/rustic/blob/72522a18f2d68e7b617c2a0a29db6556b6aeeee9/rustic-doc.el#L22 but if you can't reproduce it, I'm not sure anymore.

**Comment by brotzeit** [comment]
You're right this should throw an error. I remember that we added the require of rustic-doc not too long ago.

**Comment by brotzeit** [comment]
@KaranAhlawat can you please try it with the newest commits.

**Comment by KaranAhlawat** [comment]
> @KaranAhlawat can you please try it with the newest commits.

Sure, I'll give it a whirl. And I'll also share my config if it does not work. Sorry for the late check-in

**Comment by KaranAhlawat** [comment]
To answer you question, no, it wasn't about rustic-doc. Just rustic in general. And the latest commits seem to have fixed it, everything is working as expected. Thanks again for all your hard work! Closing this now.

**Comment by brotzeit** [comment]
:+1:
