### ISSUE TITLE
xterm-color fails to download from melpa

### ISSUE THREAD

**Issue by dredozubov** [brotzeit/rustic#398]
Installing rustic from Melpa with `package-install` results in a failure:

```
Contacting host: melpa.org:443
helm-M-x-execute-command: https://melpa.org/packages/xterm-color-20191002.2158.el: Not found
```

**Comment by psibi** [comment]
You have to do `package-list-packages` to fetch the latest package. And then you can do `package-install` for it to work.

**Comment by dredozubov** [comment]
I ran `package-list-packages` before creating this issue, so I think it's unrelated. I can't reproduce it now with the same steps, closing.
