### ISSUE TITLE
I think that nightly has become unnecessary

### ISSUE THREAD

**Issue by ncaq** [brotzeit/rustic#40]
rustic require nightly, example
* README <https://github.com/brotzeit/rustic#clippy>
* <https://github.com/brotzeit/rustic/blob/1eb91aa35f0a06752a5e0586792f4d71ccb116ac/rustic-lsp.el#L74>.

However, clippy is stable now.
I think unnecessary nightly.
I want rustic to be stable for avoid broken nightly build to happy.

**Comment by brotzeit** [comment]
Makes sense. I think we should add a `defcustom`. Want to give it a try ?

**Comment by ncaq** [comment]
I do not think that even a custom is necessary.
Because, as far as I can see, clippy and rls are in stable too.
Any other components used by rustic?

**Comment by brotzeit** [comment]
I just realized this stuff is obsolete. This is handled by lsp-mode completely now. I will remove it.
