### ISSUE TITLE
`rust-analyzer` not found

### ISSUE THREAD

**Issue by m-cat** [brotzeit/rustic#403]
`rust-analyzer` was not installed for me automatically, although it seems to be the default lsp-server for Rustic.

I had to go here and manually install it:

https://rust-analyzer.github.io/manual.html#installation

I *also* needed to change the client before everything finally worked:

```el
(setq rustic-lsp-client 'eglot)
```

The Readme should be updated to mention these fixes in `Installation` as well as `Troubleshooting`. I spent a lot of time scouring the web to find out about these fixes. 

Dropping this here in case it helps someone else.

**Comment by brotzeit** [comment]
I understand that it can be confusing with all the different packages, but automatic server installation is a lsp client feature. rustic only provides some code that's supposed to simplify setting up lsp.

I'm not sure why you had to use eglot, but sometimes rust-analyzer changes options that then has to be updated in lsp clients like https://github.com/emacs-lsp/lsp-mode/commit/d1178661020d0c1710963dcefe02fa5bf2f91bad

Thanks for helping others this way, but I'm often not sure how to document this kind of issues so it's helpful for other users. Do you think this would have helped you https://github.com/brotzeit/rustic/pull/409 ?

**Comment by m-cat** [comment]
I'll raise a quick PR.

**Comment by brotzeit** [comment]
That would be great, thanks.
