### ISSUE TITLE
Requiring rustic will break format before save in go-mode.

### ISSUE THREAD

**Issue by drshapeless** [brotzeit/rustic#413]
This is a weird bug. I program in both rust and go, using eglot. 

`(require 'rustic)` will lead to go mode being unable to format buffer before save, eglot would tell me the gopls server has no formatting capability.

Here is some my config of go and eglot, which is direct copy of the configuations in [gopls](https://github.com/golang/tools/blob/master/gopls/doc/emacs.md).
```
(defun eglot-format-buffer-on-save ()
  (add-hook 'before-save-hook #'eglot-format-buffer -10 t))
(add-hook 'go-mode-hook #'eglot-format-buffer-on-save)
```

I have no idea why rustic will have anything to do with go or eglot, this is observation. I am sure requiring rustic is the root of the bug.

**Comment by brotzeit** [comment]
And yes that wasn't ideal. I wonder if the eglot variable was buffer local before...

**Comment by brotzeit** [comment]
Thanks for the issue, can you give it a try(should be working).

**Comment by drshapeless** [comment]
Thank you for your quick response. The bug is solved. Everything is working now.
