### ISSUE TITLE
Problem with local environments (`envrc`)

### ISSUE THREAD

**Issue by dschrempf** [brotzeit/rustic#420]
When using local environments with `envrc`, compilation fails because `cargo` is not found [1]. This is, because compilation is performed in a temporary buffer, and the local environment is not copied over. There has been a fix in `rust-mode` [2,3], but the relevant function `rust-buffer-project` is not used by `rustic`. Instead, `rustic-buffer-workspace` is used, which seems to be identical or at least very similar. Could we also implement the fix into the function used by `rustic`, or remove the duplicated code and use `rust-buffer-project`?

Thanks for your help!

References:
- [1] https://github.com/purcell/envrc/issues/12
- [2] https://github.com/rust-lang/rust-mode/issues/446
- [3] https://github.com/rust-lang/rust-mode/pull/447/files

**Comment by dschrempf** [comment]
Thank you!

I do not know why, but the PR doesn't work for me. I am now using [inheritenv](https://github.com/purcell/inheritenv) like so:

```lisp
(use-package! inheritenv)
;; See https://github.com/brotzeit/rustic/issues/420.
(after! rustic (inheritenv-add-advice #'rustic-compilation))
```

It may be easier to use the `inheritenv` macro from that (tiny) package also in your case!

**Comment by NANASHI0X74** [comment]
I'm having this issue as well and neither updating rustic nor inheritenv work for me :/

**Comment by brotzeit** [comment]
Please reopen or comment in case it's still not working with https://github.com/brotzeit/rustic/pull/486

**Comment by dschrempf** [comment]
Works for me, without workaround! Thank you!
