### ISSUE TITLE
Open docs.rs for the symbol under the cursor

### ISSUE THREAD

**Issue by smallstepman** [brotzeit/rustic#422]
Hi, first of all, thank you for your work!

I wanted to bring to your attention this [rust-analyzer feature](https://www.reddit.com/r/rust/comments/w7cf7d/rustanalyzer_tip_open_docsrs_for_the_symbol_under). Is this already implemented?

**Comment by psibi** [comment]
Yes, it is: `lsp-rust-analyzer-open-external-docs`

**Comment by smallstepman** [comment]
thanks, awesome! closing
