### ISSUE TITLE
evil-write-all not triggers rustic format

### ISSUE THREAD

**Issue by cs50Mu** [brotzeit/rustic#424]
I have the following in my conf:

```lisp
  (setq rustic-format-on-save t)
  (setq rustic-format-trigger 'on-save)
```
I use evil-mode

when I press `:w`, which invokes `evil-write`, the buffer is formatted by rustic, but when I press `:wa`, which invokes `evil-write-all`, the buffer doesn't get formatted

**Comment by brotzeit** [comment]
The first option is outdated, the second should be enough. You don't use something like doom-emacs right ?

**Comment by cs50Mu** [comment]
> 

no, I don't use anything like doom-emacs

**Comment by brotzeit** [comment]
Should be working now.

**Comment by cs50Mu** [comment]
Thanks for the quick response! It seemed not in MELPA yet, I will confirm if it works ASAP

**Comment by plumenator** [comment]
This fix seems to have introduced a sort of a regression. None of the shortcuts that `save-some-buffers` supports now work. For example, `!` to save all the buffers without asking. Now one has to type "yes" (instead of just `y` or `SPC`) for each file that needs saving.

**Comment by brotzeit** [comment]
Does https://github.com/brotzeit/rustic/pull/446 work ?

**Comment by brotzeit** [comment]
Should be working now for both `compilation-ask-about-save` and `buffer-save-without-query`
