### ISSUE TITLE
Add missing dependencies automatically on using `use <pkg>`

### ISSUE THREAD

**Issue by Atreyagaurav** [brotzeit/rustic#428]
Based on https://github.com/brotzeit/rustic/releases/tag/3.3 where the following feature was introduced 

> `rustic-cargo-add-missing-dependencies`: add missing dependencies to Cargo.toml, works with lsp-mode and eglot

Is there a way to make it a variable which if true it'll be added automatically? I think lsp in C adds headers automatically when you use a function from un-included libraries.

Ideally when you do `use <something>;` just on that line. I think. Can't currently remember how lsp provides completions on use. But if we can modify it, the completions could be made with already available crates on top and also crates that can be added to Toml so if they're chosen it activates the add to toml function. Might have to use/update a list of available crates from cargo locally for that though.

If it becomes too complex or not possible (doubt that considering it's emacs) then doing it automatically on save is also fine.

**Comment by brotzeit** [comment]
> Ideally when you do use <something>; just on that line. I think. Can't currently remember how lsp provides completions on use.

I don't think the lsp server let's us know that the completion candidates are crates. But we would also have to check every completion answer from the lsp server so I think we can just check the diagnostics instead.

lsp-mode provides `lsp-diagnostics-updated-hook` which we could use to check for 'unresolved import' errors every time we receive new diagnostics. I'll give this a try, maybe it works.

> Might have to use/update a list of available crates from cargo locally for that though.

cargo edit seems to do this for us.

**Comment by brotzeit** [comment]
In case you are using lsp-mode, can you give #429 a try. Seems to be working.

**Comment by Atreyagaurav** [comment]
Yes it works, thank you. And sorry for late response took me a while to figure out how to re-load `rustic` from the git clone instead of automatic load of install. Ended up just loading the changed files manually and set the variable.
