### ISSUE TITLE
Add rustic-cargo-test-current

### ISSUE THREAD

**Issue by TatriX** [brotzeit/rustic#43]
Hi!
It would be nice to have function similar to one in [cargo](https://github.com/kwrooijen/cargo.el) package:
```
C-c C-c C-f | cargo-process-current-test.
```
It runs test near the point, which is very useful during development when you want to run one specific test.

**Comment by brotzeit** [comment]
Yeah, I already thought about adding this. I'm not sure when I will take the time to do it, but I would also gladly merge PRs.
