### ISSUE TITLE
how can i config the rust-analyzer?

### ISSUE THREAD

**Issue by billnote** [brotzeit/rustic#431]
how should i config the rust-analyzer?
 In VSCode I can use {PROJECT_DIR}/.vscode/settings.json file. But what is way on the rustic.

Thanks a lot

**Comment by psibi** [comment]
You have to configure lsp-mode for it. The documented available configurations are here: https://emacs-lsp.github.io/lsp-mode/page/lsp-rust-analyzer/#available-configurations

**Comment by brotzeit** [comment]
If you have any further questions, you can open an lsp-mode issue.
