### ISSUE TITLE
`cargo locate-project` returned status 101

### ISSUE THREAD

**Issue by Jemoka** [brotzeit/rustic#432]
Hi all! I was trying to edit a remote file and invoking `rustic-cargo-run` when I got the above error. Tracing back the error, I located this line of code:

https://github.com/brotzeit/rustic/blob/f57cce4a8faf243b8b6541554d2a9fb134214201/rustic.el#L82

which invokes cargo via `call-process`. I don't believe this command respects the remote status of the `default-directory`, which means if `cargo` is available at both the local machine and tramp, it may not use the right version of cargo. Changing this function to call `cargo` using `process-file`, which does respect `default-directory`, seemed to enable `rustic-cargo-run` on my end to work.

I didn't want to make a PR in case I was missing something in my setup. Thanks so much for your help!

**Comment by brotzeit** [comment]
Thanks for the bug report. I just realized I missed your proposed fix. Can you open a pull request with your changes ?

**Comment by Jemoka** [comment]
@brotzeit thank you! Please take a look
