### ISSUE TITLE
Run arguments

### ISSUE THREAD

**Issue by italoaa** [brotzeit/rustic#438]
It seems that after running "rustic-cargo-run" with one argument after a bit it gets saved and now I am not prompted to reenter the arguments. Maybe this is the work done by other packages. I am uding doom emacs btw.

**Comment by psibi** [comment]
What do you mean by running with one argument ?  Can you include concrete steps so that I can reproduce it at my end.

`rustic-cargo-run` is meant for non-interactive programs.

**Comment by brotzeit** [comment]
Is this also the case for other cargo commands ?

**Comment by psibi** [comment]
@italoaa Can you provide us the additional information asked in the above comments ?

@brotzeit  What do you think about closing the issue in a week if we don't get enough information by then as there is no way to reproduce without it ?

**Comment by brotzeit** [comment]
:+1:
