### ISSUE TITLE
rustic-rustfix doesn't apply fixes

### ISSUE THREAD

**Issue by kootenpv** [brotzeit/rustic#449]
So basically rustfix identifies I should add `.0` to an integer to make it a float

```
help: consider using a floating-point literal by writing it with `.0`
    |
632 |                     match self.test(self.data, qty + 1.0, ts, None) {
    |                                                       ++
```

but I understood that `rustic-rustfix` will then apply the fix? I didn't see it happen so wonder what is wrong

**Comment by brotzeit** [comment]
That's an old command, can you try `rustic-cargo-clippy-fix` instead. I forgot to remove rustfix, or make it an alias.

**Comment by brotzeit** [comment]
Sorry for the late reply.

> Is that really supposed to apply help: consider using a floating-point literal by writing it with .0``?

I think it isn't. I've tried the command with warnings and it gets fixed. So I guess it's a clippy "issue". Did you try the command from a shell ? Should be the same result.

If you still encounter issues with commands, feel free to reopen the issue or open a new one.

**Comment by kootenpv** [comment]
Could you give an example of a (reproducible warning that gets fixed?

**Comment by brotzeit** [comment]
It seems to me that your example won't be fixed for a reason since it should be fairly simple for clippy to fix it.

> I guess the amount of things it can fix is just rather limited.... only some warnings?

I'm not sure how many warnings can be fixed but I would assume most can be fixed.
