### ISSUE TITLE
rustic-format-region can not work

### ISSUE THREAD

**Issue by yuchunzhou** [brotzeit/rustic#451]
here is the error message
```
 Error: file `cargo` does not exist
 Error: file `+nightly` does not exist
 Error: file `fmt` does not exist
 Error: file `--unstable-features` does not exist
 Error: file `--file-lines` does not exist
 Error: file `[{"file":"/home/frank/dbdump/src/main.rs","range":[10,33]}]` does not exist
 Error: file `--` does not exist
```

**Comment by brotzeit** [comment]
Sorry for not answering, I already looked at the issue but I couldn't fix it yet. I think we can remove +nightly as it has landed in stable toolchain. Is it possible that this issue only occurs when you don't have nightly toolchain available ?

**Comment by yuchunzhou** [comment]
I don't think so :(, my laptop has nightly toolchain.

**Comment by brotzeit** [comment]
I'll try to fix it.

**Comment by brotzeit** [comment]
Should be working with #459. Please reopen if it still doesn't work.

**Comment by yuchunzhou** [comment]
Thanks @brotzeit, it's ok now.
