### ISSUE TITLE
rustic-cargo-current-test fails when no test is found

### ISSUE THREAD

**Issue by TatriX** [brotzeit/rustic#46]
Running `rustic-cargo-current-test` when `(rustic-cargo--get-current-fn-fullname)` returns `nil` will trigger an error. For example when one press `C-c C-c C-c` on the `pub fn`.
The bug itself is easily solvable by checking that `fullname` exists.

But I'm thinking that it can be useful to change this keybinding to `cargo-dwim` which will either run current test or for example cargo check, if no test can be found. What do you think?

**Comment by brotzeit** [comment]
Hmmm. Maybe a prompt should be opened to ask the user which test(s) he wants to run. When running this command the user expects to run a test, why should he suddenly want to use a totally different command ?

**Comment by TatriX** [comment]
The idea is to bind `C-c C-c C-c` to `rustic-cargo-dwim`, so it does something meaningful in the current context. If I'm writing a test, run current test for me. If I'm in the /tests or in tests mod, run the whole test suite, otherwise run cargo check.

**Comment by brotzeit** [comment]
Ok.

**Comment by zhenwenc** [comment]
Also, the `rustic-cargo--get-current-fn-fullname` result is incorrect when there is `use ...;` inside the test `fn`, which is a normal case when using `diesel`, see [example](https://github.com/diesel-rs/diesel/blob/v1.3.0/examples/postgres/all_about_inserts/src/lib.rs#L54).

**Comment by brotzeit** [comment]
Please reopen this issue if you notice new issues with this function.
