### ISSUE TITLE
having trouble with adding rustic

### ISSUE THREAD

**Issue by Chaqua** [brotzeit/rustic#461]
When I add the following to my config:
`(use-package rustic)
(setq package-archives '(("melpa" . "http://melpa.org/packages/")
                         ("gnu" . "http://elpa.gnu.org/packages/")))`

And I try to compile it, it tells me "file-missing Cannot open load file No such file or directory rustic"

**Comment by brotzeit** [comment]
Does it work with the updated readme in https://github.com/brotzeit/rustic/pull/464 ?

**Comment by brotzeit** [comment]
If it still doesn't work, please reopen the issue.

Btw I recommend using straight.el instead of emacs built-in package.el.

**Comment by Chaqua** [comment]
Well I setup everything from scratch again because I was bored anyways and it works totally fine now. Sorry, I forgot abt opening a Issue, should have backed it up to see if it works now.
