### ISSUE TITLE
Scroll compilation output buffers

### ISSUE THREAD

**Issue by rittelle** [brotzeit/rustic#462]
I noticed that the output buffers for compilation or tests fill up, but doesn't scroll when the output doesn't fit in the window.  I always find myself directly selecting the window and scrolling down.
Would automatically scrolling to the bottom be a potential feature of rustic or is that something that I, the user, have to configure myself?

**Comment by brotzeit** [comment]
It's a feature of emacs that's reused by rustic. Does https://github.com/brotzeit/rustic/pull/463 help you ?
