### ISSUE TITLE
rustic-run-arguments does not work

### ISSUE THREAD

**Issue by iitalics** [brotzeit/rustic#470]
rustic-cargo-run when invoked from eval-expression or from pressing C-c C-c C-r or from the popup buffer does not look at the `rustic-run-arguments`. Also the behavior of using the `compile-history` variable does not make any sense because `compile-history` is usually set to an entire shell command like `make`, not a set of argument flags, so to use that feature you have to first invoke a nonsensical flag as the compile command and then use cargo run.

**Comment by brotzeit** [comment]
>  Also the behavior of using the compile-history variable does not make any sense because compile-history

`compile-history` is only supposed to be rustic with `rustic-compile` and not the cargo commands. I didn't review properly when I merged this.

**Comment by psibi** [comment]
@iitalics Can you give it a try with this PR and see if it works for you: https://github.com/brotzeit/rustic/pull/474 ?

**Comment by psibi** [comment]
Please re-open if it is still reproducible after https://github.com/brotzeit/rustic/pull/474
