### ISSUE TITLE
rust-analyzer failed to discover workspace

### ISSUE THREAD

**Issue by skittishdev** [brotzeit/rustic#471]
Hi,

This may not be a rustic issue, but I didn't know where else to start. Fairly new to both Emacs and Rust.

I have a simple cargo project structured like this:
```
project-name
├── src                     # Contains 1 file - main.rs
└── Cargo.toml
```

I am using eglot and rustic with minimal config with vanilla Emacs.
```
(use-package rustic
  :custom
  (rustic-lsp-client 'eglot)
  (rustic-analyzer-command '("/usr/local/bin/rust-analyzer")))
```

I also use emacs in server mode, and this is how I open files generally
```
emacsclient -c src/main.rs &
```

> Expected behavior:

rust-analyzer is able to detect that I am in a cargo project/workspace, and there are no error messages.

> Actual behavior:

I see an error message from eglot that rust-analyzer failed to discover workspace. 

> What I tried:

After checking out a few issues, I enabled rustic's detached file support, and the error disappeared, and flycheck, completion-at-point etc. started working as expected! It is unclear to me though why I have to enable detached file support, esp. when I'm inside a cargo project. But I could be misunderstanding something.

This is the configuration that works:
```
(use-package rustic
  :custom
  (rustic-lsp-client 'eglot)
  (rustic-analyzer-command '("/usr/local/bin/rust-analyzer"))
  (rustic-enable-detached-file-support t)) ;; enable this until we figure out how to get rust-analyzer to autodetect the workspace
```

> What I'm looking for:

How can I get rust-analyzer to detect the cargo workspace automatically with rustic? Is there any additional config I need to provide? What am I missing?

**Comment by brotzeit** [comment]
> It is unclear to me though why I have to enable detached file support, esp. when I'm inside a cargo project. But I could be misunderstanding something.

You can find the explanation here https://github.com/brotzeit/rustic/issues/391.

Sorry but I can't change anything about eglot.
