### ISSUE TITLE
Improve expand macro and LSP integration

### ISSUE THREAD

**Issue by psibi** [brotzeit/rustic#473]
Right now, this functionality is implemented as part of `rustic-analyzer-macro-expand` function. But it has a couple of issues:

- It wraps the expanded macro in a main function so that rustfmt can be run on it. This leads to wrong code in most cases: All the expanded code is present inside the main function, when it is not the case. So probably after we do the formatting step, we should remove the main block. (This leads to a even more confusing situation when we use tokio::main macro. We have two main functions!)
- When we try to do `rustfmt` on the expanded code, it almost always fails for me. These are some of the error messages:

```
error: expected identifier, found keyword `let`
 --> <stdin>:3:9
  |
2 |     let body = async {
  |                ----- `async` blocks are only allowed in Rust 2018 or later
3 |         let Cmd { opt, subcommand }: Cmd = Cmd::parse();
  |         ^^^ expected identifier, found keyword
  |
  = help: pass `--edition 2021` to `rustc`
  = note: for more on editions, read https://doc.rust-lang.org/edition-guide
```

In my opinion, we should to this change:

- Do not try to format the macro as the response from the language server comes in the formatted fashion: https://github.com/rust-lang/rust-analyzer/pull/12014
- Avoid the extra wrapping to please `rustfmt` as it's not required anymore.

I will be happy to provide a patch if there are no objections.

**Comment by brotzeit** [comment]
> Do not try to format the macro as the response from the language server comes in the formatted fashion

Great, I wonder why this wasn't added earlier. I expected issues with the wrapping, but the feature didn't seem very convient to me when the output is not formatted.

> I will be happy to provide a patch if there are no objections.

Thanks!
