### ISSUE TITLE
org-mode can not be used

### ISSUE THREAD

**Issue by improve100** [brotzeit/rustic#482]
error: failed to parse manifest at `/tmp/babel-QBo58A/cargoE5sXAi/Cargo.toml`
Caused by:
  this virtual manifest specifies a [dependencies] section, which is not allowed

Check this file only dependencies
$cat Cargo.toml
[dependencies]

When I use cargo new helloworld on the terminal is ok. 
$ cat Cargo.toml
[package]
name = "helloworld"
version = "0.1.0"
edition = "2021"
#See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]

**Comment by brotzeit** [comment]
Can you show me the babel block you are using ?

**Comment by improve100** [comment]
#+BEGIN_SRC rustic :tangle ~/rust/helloworld/src/main.rs   :tangle-mode (identity #o755) :padline no
fn main() {
    println!("hello rust!");
    let gate = "rust";
    // println!("hello {gate}");
    println!("hello {}", gate);
    // let mut x = 5;
    // println!("hello {x}");
}
#+END_SRC

**Comment by improve100** [comment]
I reinstalled the rust mode. The problem disappeared

**Comment by psibi** [comment]
For some reason, I reproduced the same issue. Installing the stable toolchain via rustup and after restarting the Emacs server - I wasn't able to reproduce it anymore.

And when I was able to reproduce the issue, the `Cargo.toml` was similar to how you have reported:

```
[dependencies]
serde = {version = "*"}
regex = {version = "*"}
```

It didn't have the `package` section causing it to throw an error like this.
