### ISSUE TITLE
Unable to use rust-analyzer when installed via rustup

### ISSUE THREAD

**Issue by jdortiz** [brotzeit/rustic#487]
Hello and thank you for this package.

I used to have rust-analyzer installed from the source code using `cargo xtask install`. But since `rustup` allows installing rust-analyzer as a component, I have switched to that method. However, I have been unable to configure rustic to use that version of rust-analyzer. That version can be run using `rustup run stable rust-analyzer`, but if I use that command in the configuration with this variable:
```
(setq rustic-analyzer-command '("rustup run stable rust-analyzer"))
```
I get this error:
```
(file-missing "Searching for program" "No such file or directory" "rustup run stable rust-analyzer")
```
It also fails if I use the path to the rustup command.

I understand that it is expecting the path to the rust-analyzer binary rather than a command with parameters to execute it. I also know that I could use the path to the rustup component (e.g. "~/.rustup/toolchains/stable-x86_64-apple-darwin/bin/rust-analyzer"), but that would result in an architecture/toolchain dependent configuration, making it unsuitable for sharing between my Intel and M1 machines.

What is the proper way to do this? Thank you.

Best regards,

  Jorge

**Comment by brotzeit** [comment]
Does it work when you make it a list instead of a string ?

**Comment by jdortiz** [comment]
It does! Thank you!

Keep up the excellent work.

Best regards,

  Jorge

**Comment by brotzeit** [comment]
:+1:
