### ISSUE TITLE
Rust analyzer cannot find Cargo.toml file 

### ISSUE THREAD

**Issue by sehnsucht13** [brotzeit/rustic#50]
Hi, first of all, good job on this package! It is awesome but I have run into a bit of an issue. When I use rustic with rust-analyzer in the remacs repository, the `Cargo.toml` file is not in the project root(it is in `rust_src` instead of the main `remacs` folder where the `.git` folder is). Due to this, rust-analyzer cannot locate it and it signals an error. Seems like the issue is brought on by passing the project root directly to rust analyzer and this can cause problems in repositories such as this one.

I will look into this later when I have the time but the solution should be pretty simple(unless I am missing something completely obvious in which case, please correct me!):
- Start at project root
- Look for `Cargo.toml` recursively
- If not found,  signal an error to the user
- If found, pass that directory instead of project root to rust-analyzer

Thanks again for your work!

**Comment by brotzeit** [comment]
Thanks for the bug report. I know this issue with remacs, but I couldn't decide how to handle this. I will take a look at it.

**Comment by sehnsucht13** [comment]
I will try to implement something this weekend. I think that the sequence of actions I proposed in my original issue might do the trick. The only drawback is that it might be a bit slow in large repo's. Perhaps we could add an option to specify the root on a per case basis if necessary. Usually, most rust repo's will have the `Cargo.toml` file in the root so repo's which are exceptions should not be too many and the user will most likely be able to manage them easily by hand.

**Comment by sehnsucht13** [comment]
Small update to this, I think I found a clean solution to this:
https://doc.rust-lang.org/cargo/commands/cargo-locate-project.html

Apparently there is a command to locate the Cargo.toml file of the project. It does not seem to be documented in the `help` section of cargo cli but it is in the book. We could use this to quickly find the root instead of traversing and looking for it in any way. I will hopefully be free tommorow and try to get this going.

**Comment by brotzeit** [comment]
I think I've tried something similiar when I started this fork. But I dropped it in favor of the current implementation, since we don't have to start a subprocess every time since function is called.

And remacs seems to be one of the few projects that have this issue. Maybe we can add an option. Most people won't need this so this might be the best.

**Comment by sehnsucht13** [comment]
Yea you are right. Remacs seems to be pretty unique. I guess we can add an option where if Cargo.toml is not found then the user can pick its directory/path to it and that can be passed as the project directory to rust analyzer.

**Comment by brotzeit** [comment]
Yeah, I also thought about this solution.

**Comment by brotzeit** [comment]
It seems to be working now. Please reopen this issue if you still have issues.
