### ISSUE TITLE
version check issues?

### ISSUE THREAD

**Issue by johnstonskj** [brotzeit/rustic#502]
When I run `rustic-doc-setup` I get the following messages:

```
Your version of fd is too old, please install a recent version, maybe through cargo.
Your version of pandoc is too old, please install a more recent version. See their github for more info.
```

However I have both installed by brew on macos and have done specific upgrades to both to get them to the latest versions:

```bash
❯ pandoc --version
pandoc 3.1.2
❯ fd --version
fd 8.7.0
```

**Comment by IT-Luka** [comment]
Doom Emacs,

When running rustic-doc-setup through M-x:

> Your version of pandoc is too old, please install a more recent version. See their github for more info.

I've tried it with version 3.1.2 (newest on arch), and 3.1.4 (newest on github), same result

Running (rustic-doc-setup) in ielm or eshell also gives this error:

> Symbol’s function definition is void: rustic--inheritenv

**Comment by whompyjaw** [comment]
I am getting the same issue using Doom Emacs. Using 3.1.7 of pandoc (newest version per their github)

**Comment by Padswynn** [comment]
Same problem:
```
GNU Emacs 29.3
Copyright (C) 2024 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

pandoc 3.1.3
Features: -server +lua
Scripting engine: Lua 5.4
User data directory: /home/username/.local/share/pandoc
Copyright (C) 2006-2023 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.

rustup 1.27.1 (54dd3d00f 2024-04-24)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.78.0 (9b00956e5 2024-04-29)`

fd 10.1.0
```

I have tried buildign pandoc from source to get to a more recent version, but nothing is working.

full error that i get:
```
Your version of fd is too old, please install a recent version, maybe through cargo.
Your version of pandoc is too old, please install a more recent version. See their github for more info.
rustic-doc--start-process: Invalid function: rustic--inheritenv
Could not finish process: exited abnormally with code 1
```

I would like to add that I have tried with fd-find being intalled by my package manager and by cargo. When I install FD through cargo it gives the above error, however the `fd is too old` line is gone when fd-find is installed through distro repository.

**Comment by Velnbur** [comment]
From code I see that problem is not related to `fd` at all:

https://github.com/brotzeit/rustic/blob/39423d1cf4fa054c36bf9577356451f4c06ee148/rustic-doc.el#L282

For some reason only the minor version of `fd` is checked. To prove that, after running this line, I get:

```sh
$ fd --version
fd 10.1.0
```

And after running `elisp` code:

```elisp
(substring (shell-command-to-string "fd --version") 3 4) => "1"
```

The same thing with `pandoc`:

https://github.com/brotzeit/rustic/blob/39423d1cf4fa054c36bf9577356451f4c06ee148/rustic-doc.el#L286

```sh
$ pandoc --version
pandoc 3.1.11.1
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /Users/velnbur/.local/share/pandoc
Copyright (C) 2006-2023 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```

```elisp
(substring (shell-command-to-string "pandoc --version") 9 11) => "1."
```
