### ISSUE TITLE
Customize cargo output following

### ISSUE THREAD

**Issue by JoeOsborn** [brotzeit/rustic#51]
I prefer that compilation and similar buffers not scroll automatically on new output.  Rustic seems to override that behavior for cargo commands—can we get a defcustom or something to change that behavior or possibly use the existing settings for compilation mode following output?  I can add a defadvice or something as a stopgap but it feels like a bug since the cargo process mode “acts like” a compilation mode.

Thanks for your great work on rustic-mode!

**Comment by brotzeit** [comment]
Hmmm, I'm not sure I understand. Do you mean the cursor position in the compilation buffer(cargo commands use a derived compilation mode) after you started your command ?

**Comment by JoeOsborn** [comment]
Yes, point (and scrolling) always end up at the bottom of e.g. “cargo build”, while I want to see the very first error or whatever and not the last.

**Comment by brotzeit** [comment]
Sure, I will change that.

**Comment by JoeOsborn** [comment]
Thanks!  I get that for `cargo run` it’s useful because it’s more like regular comint (may want to read lines or characters, for example), but most of the others (clippy, etc) seem more like compilation modes.

**Comment by brotzeit** [comment]
Yeah, I get what you mean.

**Comment by brotzeit** [comment]
I just noticed there's already a defcustom for this in compile.el `compilation-scroll-output`.

**Comment by JoeOsborn** [comment]
Yes, I have it set but it looks like my setting is not being used in the rustic cargo buffers.

**Comment by brotzeit** [comment]
The variable isn't considered at all. rustic doesn't use `compilation-start`.
rustic shouldn't use it's own function for this and try to keep its modifications by using defcustoms like `compilation-environment`. But I don't know how to change the `:coding` of a process through the compile.el interface.
If anybody knows how to modify this would be a great help.

**Comment by brotzeit** [comment]
Take a look at #52.

**Comment by JoeOsborn** [comment]
Looks great, thanks!
