### ISSUE TITLE
rust-analyzer cannot be used with (setq rustic-lsp-server 'rust-analyzer)

### ISSUE THREAD

**Issue by FirstLoveLife** [brotzeit/rustic#61]
I set       (setq rustic-lsp-server 'rust-analyzer)    after lsp-mode startup and C-h o rustic-lsp-server:
```
rustic-lsp-server is a variable defined in rustic-util.el.

Value
rust-analyzer

Original Value
rls
```

modes for rs files:

```

(Information about these minor modes follows the major mode info.)

Rust mode defined in ‘rustic.el’:
```

lsp-log:
```
Command "rls" is present on the path.
Found the following clients for /home/firstlove/projects/rust/guess/src/main.rs: (server-id rls, priority -1)
The following clients were selected based on priority: (server-id rls, priority -1)
Creating watch for /home/firstlove/projects/rust/guess/
Failed to create a watch for Could not add watch for file: No space left on device, /home/firstlove/projects/rust/guess: message
Building - guess
Building - guess cfg(test)
```
rust analyzer has also been installed in PATH:
```
chenli% ls | grep ra 
ra_lsp_server
```

**Comment by brotzeit** [comment]
I have to take a look at this.

**Comment by brotzeit** [comment]
Do you use eglot or lsp-mode ?

**Comment by FirstLoveLife** [comment]
> Do you use eglot or lsp-mode ?

Yes. I'm using lsp-mode

**Comment by tarka** [comment]
I can confirm similar behaviour with eglot; rls is started instead of ra_lsp_server. Rustic 20190910.725 (melpa). Config:

    (use-package rustic
      :pin melpa
      :config
      (setq rustic-lsp-server 'rust-analyzer)
      (setq rustic-rls-pkg 'eglot)
      (setq rustic-format-on-save nil)
      (define-key rustic-mode-map (kbd "TAB") #'company-indent-or-complete-common))

**Comment by brotzeit** [comment]
lsp-mode should be working again, but I have to make some small changes to make rust-analyzer work with eglot.

**Comment by brotzeit** [comment]
I added some stuff. If it still doesn't work with `eglot` feel free to reopen the issue.
