### ISSUE TITLE
rustfmt syntax error buffer

### ISSUE THREAD

**Issue by rakanalh** [brotzeit/rustic#63]
Hello,

I noticed that when you modify & save the current file, rustfmt would be triggered. In case of syntax errors, rustfmt would cause a new buffer to be opened with the errors listed.

Is there a way to disable this new buffer? the behavior is pretty annoying and it would be nice if rustfmt can still be enabled but no buffers are opened automatically when syntax errors exist in the file.

**Comment by brotzeit** [comment]
Do you want a message in the echo are or no notification at all ?

**Comment by rakanalh** [comment]
a message in the echo area won't bother me much compared to opening the buffer. But no notification at all would be fine as well.

Thank you @brotzeit

**Comment by brotzeit** [comment]
You can set `rustic-format-display-method` to `'ignore`.

**Comment by rakanalh** [comment]
Cool, that works. Will close the issue but i think those options should be documented.

Many thanks for the package & for your support.

**Comment by brotzeit** [comment]
Yeah I'm just adding additional docs and will include this. Thanks for the feedback!
