### ISSUE TITLE
Add option for rustfmt before compile

### ISSUE THREAD

**Issue by phillord** [brotzeit/rustic#64]
I find the "rustfmt on save" functionality very jarring because it can cause another buffer to pop up on save. I tend to save a lot (muscle memory for the days computers used to crash all the time) and this is totally unexpected from a user perspective.

But I don't want rustfmt to be totally manual, since I know I will just forget to do it. Having it run immediately before a compile/test would be great though -- failure would stop the compile/test.

**Comment by brotzeit** [comment]
Sounds like a great idea!

**Comment by brotzeit** [comment]
I guess you want to use `cargo fmt` for this ?

**Comment by brotzeit** [comment]
#66
