### ISSUE TITLE
Make rustic respect compilation-scroll-output when set to first-error

### ISSUE THREAD

**Issue by brotzeit** [brotzeit/rustic#67]
#51

**Comment by TatriX** [comment]
Compilation scroll behavior seems to randomly break.
After a cold start it respects `(setq compilation-scroll-output nil)` but then after some random event it ignores it. I wasn't able to find any reproducible way to trigger it. After that I have to kill `*rustic-compilation*` buffer to make it work again.

Another thing: after first `rustic-cargo-check`, `next-error` doesn't work saying something like 'user-error: Moved past last error`. To make it work I either have to focus `*rustic-compilation*`  or use `next-error-select-buffer`.

**Comment by brotzeit** [comment]
Thanks for the bug report(s). Can you do me a favor and open a new issue for each of this bugs. I will try to fix this.

**Comment by grease-and-co** [comment]
It seems adding

> (if (or compilation-auto-jump-to-first-error
> 	(eq compilation-scroll-output 'first-error))
>     (set (make-local-variable 'compilation-auto-jump-to-next) t))

to rustic-compilation-setup-buffer solves problem when you expect compilation to scroll to first error.

**Comment by brotzeit** [comment]
@grease-and-co I've tried it and it seems to work, thanks.
