### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by worikgh** [brotzeit/rustic#69]
Using `package-install`

```
$ emacs --version
GNU Emacs 26.1
$ cat /etc/issue
Ubuntu 19.04 \n \l
```

```
Contacting host: melpa.org:443
package-install-from-archive: https://melpa.org/packages/ht-20190830.910.el: Not found
```

**Comment by brotzeit** [comment]
Did you run `package-refresh-contents` ? I would recommend [use-package](https://github.com/jwiegley/use-package).

**Comment by worikgh** [comment]
I cannot see 
`package-refresh-contents` then `package-install rustic`
```
Importing package-keyring.gpg...done
Contacting host: elpa.gnu.org:443
Failed to download ‘gnu’ archive.
Contacting host: melpa.org:443 [2 times]
Package refresh done
Making completion list...
user-error: Beginning of history; no preceding item
Contacting host: melpa.org:443
Generating autoloads for ht.el...
Not registering prefix "ht" from ht.  Affects: ("ht" "ht<-alist" "ht<-plist" "ht?" "ht-get" "ht-get*" "ht-update" "ht-update!" "ht-merge" "ht-map" "ht-keys" "ht-values" "ht-items" "ht-amap" "ht-aeach" "ht->plist" "ht->alist" "ht-to-plist" "ht-to-alist" "ht-p" "ht-create" "ht-clear" "ht-clear!" "ht-copy" "ht-contains?" "ht-contains-p" "ht-size" "ht-set" "ht-set!" "ht-select" "ht-select-keys" "ht-remove" "ht-remove!" "ht-reject" "ht-reject!" "ht-delete-if" "ht-from-alist" "ht-from-plist" "ht-find" "ht-each" "ht-empty?" "ht-empty-p" "ht-equal?" "ht-equal-p")
Generating autoloads for ht.el...done
Wrote XXXXXXXXX.emacs.d/elpa/ht-20190924.704/ht-autoloads.el [2 times]
Checking XXXXXXXXX.emacs.d/elpa/ht-20190924.704... [3 times]
Compiling XXXXXXXXX.emacs.d/elpa/ht-20190924.704/ht.el...done
Wrote XXXXXXXXX.emacs.d/elpa/ht-20190924.704/ht.elc
Checking XXXXXXXXX.emacs.d/elpa/ht-20190924.704...
Done (Total of 1 file compiled, 2 skipped)
Contacting host: elpa.gnu.org:443
package-install-from-archive: https://elpa.gnu.org/packages/spinner-1.7.3.el: Bad Request
```

**Comment by worikgh** [comment]
Using `use-package` get: 
```
Error (use-package): Cannot load rustic
```

**Comment by brotzeit** [comment]
Does this work ?

`gpg2 --keyserver hkp://pool.sks-keyservers.net:80 --homedir $HOME/.emacs.d/elpa/gnupg --recv-keys 066DAFCB81E42C40`

**Comment by worikgh** [comment]
> I documented it in the readme. You can find instructions here https://elpa.gnu.org/packages/gnu-elpa-keyring-update.html

The instructions there fail too: 
```
Contacting host: elpa.gnu.org:443
package-install-from-archive: https://elpa.gnu.org/packages/gnu-elpa-keyring-update-2019.3.tar: Bad Request
```

**Comment by worikgh** [comment]
> gpg2 --keyserver hkp://pool.sks-keyservers.net:80 --homedir $HOME/.emacs.d/elpa/gnupg --recv-keys 066DAFCB81E42C40

That makes no difference.
I ran that command (adjusting my key store based on random titbits on the Internet makes me queasy) restarted emacs and still get: `package-install-from-archive: https://elpa.gnu.org/packages/spinner-1.7.3.el: Bad Request`

**Comment by brotzeit** [comment]
Hmm.

**Comment by brotzeit** [comment]
Can you try to completely delete your installed packages. It seems to work for everybody else.

**Comment by brotzeit** [comment]
Btw I would recommend [straight.el](https://github.com/raxod502/straight.el#install-packages). A side effect would be that you won't have any gpg related issues. I added a note to the readme.
