### ISSUE TITLE
rustfmt and auto saving doesn't work together

### ISSUE THREAD

**Issue by mikhail-krainik** [brotzeit/rustic#7]
I have my own solution for autosave buffer when the emacs last a focus and I stuck with problem when rustfmt freezed my emacs after autosave.

**Comment by brotzeit** [comment]
What exactly are you using for autosaving ? I assume it's `auto-save-visited-mode` or `auto-save-mode` ?

**Comment by mikhail-krainik** [comment]
```lisp
(defun save-all ()
  (interactive)
  (save-some-buffers t))
(add-hook 'focus-out-hook 'save-all)
```
And I detect that behaviour when I split the buffer on two window with the same file.

**Comment by brotzeit** [comment]
I had to add `rustic-save-some-buffers` because `rustfmt` is executed as an asynchronous process. I'm afraid you have to turn off `rustic-format-on-save`.

``` emacs-lisp
(defun save-all ()
  (interactive)
  (let ((rustic-format-on-save nil))
    (save-some-buffers t)))
```

**Comment by brotzeit** [comment]
Oh, I didn't know I can close issues from commits =)

Does it work with the latest commit ?

**Comment by mikhail-krainik** [comment]
Yes, it seems well.
