### ISSUE TITLE
rustic-racer-describe not working (use lsp-describe-thing-at-point instead)

### ISSUE THREAD

**Issue by graves** [brotzeit/rustic#70]
Hello, I receive the following error when running rustic-racer-describe:

Symbol's value as variable is void: tmp-file

I tried setting the following variables:

tmp-file 
tmp-file-for-stderr

and got stuck on the last error:

Invalid function: rustic-racer-with-temporary-file

**Comment by brotzeit** [comment]
Hmmm. It works if you install rustic manually. I have to take a look at this. For now you can put this in your init.el:

```
(add-to-list 'load-path "~/path/to/rustic/")
(byte-recompile-directory "~/path/to/rustic/")
(load "rustic")
```

**Comment by brotzeit** [comment]
You can use `lsp-describe-thing-at-point` instead.

**Comment by graves** [comment]
Thank you, that indeed gets the job done for now.

**Comment by brotzeit** [comment]
It seems to work with #95 thanks to @tarsius. If it still doesn't work for you with the latest changes, please reopen this issue.
