### ISSUE TITLE
Really exit Emacs? (y or n)

### ISSUE THREAD

**Issue by graves** [brotzeit/rustic#71]
is there a variable i can set to avoid this message every time i exit emacs?

**Comment by brotzeit** [comment]
This is not a default. I suppose you use something like spacemacs ?
Try `(setq confirm-kill-emacs nil)`. Not really related to this package ;)

**Comment by graves** [comment]
i guess i meant to ask this on to the doom emacs team and accidentally posted here. thank you though, your fix works.
