### ISSUE TITLE
rust-analyzer-inlay-hints-mode from rust-analyzer's emacs package

### ISSUE THREAD

**Issue by Dummyc0m** [brotzeit/rustic#73]
I noticed that rust-analyzer added a minor mode that inlays things like inferred types for bindings. Would it be possible to add it to rustic? https://github.com/rust-analyzer/rust-analyzer/blob/master/editors/emacs/ra-emacs-lsp.el#L236
Thanks!

**Comment by brotzeit** [comment]
It was part of rustic, but I moved this stuff to lsp-mode. However this is still missing. I will add the remaining features to lsp-mode the next days and document it in the wiki.
