### ISSUE TITLE
Fix smartparens

### ISSUE THREAD

**Issue by phillord** [brotzeit/rustic#74]
rustic fails with smartparens where lifetimes are used (i.e. typing `&'a` results in the matching `'` being added). rust-mode works under these circumstances, because smartparens has rust specialised support which rustic isn't using, I think.

**Comment by brotzeit** [comment]
If it works for rust-mode it probably won't be much effort to fix this for rustic. I will take a look at it.

**Comment by brotzeit** [comment]
@phillord Can you give it a try ?

**Comment by brotzeit** [comment]
I tried it, but I can't get this to work with rust-mode or rustic.

**Comment by bkchr** [comment]
So it works for me in `&'` but not when I'm in `<>`. I opened a bug report upstream for this.

**Comment by brotzeit** [comment]
@bkchr thanks for the fix!

If anybody still has issues with smartparens, please open a bug report at rust-mode. It's very unlikely that it's a rustic issue now that rustic depends on rust-mode.
