### ISSUE TITLE
lsp-ui sideline strips some text

### ISSUE THREAD

**Issue by nree** [brotzeit/rustic#78]
![Screenshot (138)](https://user-images.githubusercontent.com/12157634/69835572-b691b300-1210-11ea-8d19-3988cd98e626.png)

Emacs vs VS code

Do you know why VS Code prints the full error message while Emacs cuts out chunks of it?
It's very confusing to use like this.

I just disable lsp-ui right now. The error text shows up properly in Emacs minibuffer in this case.

**Comment by brotzeit** [comment]
Yeah, that's a known issue. @sebastiencs is working on a fix https://github.com/emacs-lsp/lsp-ui/issues/332#issuecomment-550544680

**Comment by brotzeit** [comment]
Fixed with https://github.com/emacs-lsp/lsp-ui/pull/475 ?

**Comment by brotzeit** [comment]
If this is still not solved with latest lsp-ui, please open a new issue https://github.com/emacs-lsp/lsp-ui/issues/new
