### ISSUE TITLE
Unable to set-up Rust-Analyzer

### ISSUE THREAD

**Issue by LU15W1R7H** [brotzeit/rustic#79]
I'm unable to use Rust-Analyzer.
I've set `rustic-lsp-server` to `rust-analyzer` but when I open a rust project LSP still tries to run RLS and not the analyzer.

What am I doing wrong?

**Comment by brotzeit** [comment]
Which `lsp-mode` version are you using ?

**Comment by LU15W1R7H** [comment]
I'm using the most recent version of `lsp-mode`: 20191201.854.
I've installed the rust-analyzer binary and it is in `path`.
I've removed RLS as rustup componend, so that LSP has no chance of using it but then it just fails to start the LSP-server.
I later also copied `ra-emacs-lsp.el` into my `emacs.d` and required it by emacs (I don't know if that is necessary for rustic) but it's still not working.

**Comment by brotzeit** [comment]
Can you run `ra_lsp_server` manually in your shell ?

**Comment by LU15W1R7H** [comment]
Yeah, that's working fine.

**Comment by brotzeit** [comment]
I've seen a post about melpa not being reliable regarding package versions. Please look at the file lsp-rust.el of the lsp-mode version you are using. Please confirm that there is a section for 'rust-analyzer'. It should be obvious from the code.
And also confirm that you are actualling using `(setq rustic-lsp-server 'rust-analyzer)`. The quote before rust-analyzer means it's a symbol. That's important.

**Comment by LU15W1R7H** [comment]
Yes in `lsp-rust.el` there is a section on 'rust-analyzer'. And the variable has also been set correctly: `describe-variable` tells me the value of `rustic-lsp-server` is `rust-analyzer'.

**Comment by brotzeit** [comment]
Ok then you have to enable logging and send me the contents of the log buffer -> https://github.com/emacs-lsp/lsp-mode/wiki/Debugging

**Comment by LU15W1R7H** [comment]
After opening a rust file this is the content of `lsp-log`:
`
Command "rls" is present on the path.
Found the following clients for /home/luis/dev/rust/spotify-tui/src/app.rs: (server-id rls, priority 1)
The following clients were selected based on priority: (server-id rls, priority 1)
`
And this is the content of `lsp-log: rls:3828`:
`
[Trace - 02:46:37 PM] Sending request 'initialize - (1)'.
Params: {
  "processId": 3783,
  "rootPath": "/home/luis/dev/rust/spotify-tui",
  "rootUri": "file:///home/luis/dev/rust/spotify-tui",
  "capabilities": {
    "workspace": {
      "workspaceEdit": {
        "documentChanges": true,
        "resourceOperations": [
          "create",
          "rename",
          "delete"
        ]
      },
      "applyEdit": true,
      "symbol": {
        "symbolKind": {
          "valueSet": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26
          ]
        }
      },
      "executeCommand": {
        "dynamicRegistration": false
      },
      "didChangeWatchedFiles": {
        "dynamicRegistration": true
      },
      "workspaceFolders": true,
      "configuration": true
    },
    "textDocument": {
      "declaration": {
        "linkSupport": true
      },
      "definition": {
        "linkSupport": true
      },
      "implementation": {
        "linkSupport": true
      },
      "typeDefinition": {
        "linkSupport": true
      },
      "synchronization": {
        "willSave": true,
        "didSave": true,
        "willSaveWaitUntil": true
      },
      "documentSymbol": {
        "symbolKind": {
          "valueSet": [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26
          ]
        },
        "hierarchicalDocumentSymbolSupport": true
      },
      "formatting": {
        "dynamicRegistration": true
      },
      "rangeFormatting": {
        "dynamicRegistration": true
      },
      "rename": {
        "dynamicRegistration": true
      },
      "semanticHighlightingCapabilities": {
        "semanticHighlighting": null
      },
      "codeAction": {
        "dynamicRegistration": true,
        "codeActionLiteralSupport": {
          "codeActionKind": {
            "valueSet": [
              "",
              "quickfix",
              "refactor",
              "refactor.extract",
              "refactor.inline",
              "refactor.rewrite",
              "source",
              "source.organizeImports"
            ]
          }
        }
      },
      "completion": {
        "completionItem": {
          "snippetSupport": false,
          "documentationFormat": [
            "markdown"
          ]
        },
        "contextSupport": true
      },
      "signatureHelp": {
        "signatureInformation": {
          "parameterInformation": {
            "labelOffsetSupport": true
          }
        }
      },
      "documentLink": {
        "dynamicRegistration": true
      },
      "hover": {
        "contentFormat": [
          "markdown",
          "plaintext"
        ]
      },
      "foldingRange": {
        "dynamicRegistration": true,
        "rangeLimit": null,
        "lineFoldingOnly": false
      }
    }
  },
  "initializationOptions": {
    "omitInitBuild": true,
    "cmdRun": true
  }
}
`

**Comment by brotzeit** [comment]
Ok. Try these two things and if it still doesn't work I will take a closer look at it. Maybe I made some changes that broke someting.
1) use the function `lsp-rust-switch-server` to switch priorities of rls and rust-analyzer and start lsp in a new project(this won't work if there's already a lsp process running for the current project)
2) start emacs with this config. Nothing else. And try it again.
```elisp
(use-package lsp-mode)
(use-package rustic)
(setq rustic-lsp-server 'rust-analyzer)
```

**Comment by LU15W1R7H** [comment]
Okay I got it running now, also with my own config.
But the `(setq rustic-lsp-server 'rust-analyzer)` didn't work for me. I have to `lsp-rust-switch-server` and then run `lsp` again. Then it successfully switches to rust-analyzer. Before switching it just tries to use RLS.

**Comment by brotzeit** [comment]
Hmmm, ok then I guess it's my turn.

**Comment by brotzeit** [comment]
It's really weird that I never had this problem, but shortly after you opened this issue I got the same error. I've found the solution for the problem and I'm pretty sure you have the exact same issue. Emacs doesn't seem to respect this `export PATH="$HOME/.cargo/bin:$PATH"` from your bashrc. The temporary solution for this is to put this in your config:

```elisp
(setenv "PATH" (concat (getenv "PATH") ":" (expand-file-name "~/.cargo/bin")))
(setq exec-path (append exec-path (list (expand-file-name "~/.cargo/bin"))))
```

This way emacs can open the binary and you can run rust-analyzer again. I will try to find a better way.

**Comment by tarka** [comment]
A more general solution would probably be [exec-path-from-shell](https://melpa.org/#/exec-path-from-shell).

**Comment by brotzeit** [comment]
I decided to let the user take care of this and added a note in the readme.

**Comment by LU15W1R7H** [comment]
I'm okay with that. Thanks for your time.
