### ISSUE TITLE
command rustic-cargo-popup does not exist

### ISSUE THREAD

**Issue by zhaojiangbin** [brotzeit/rustic#83]
In `rustic-compilation-mode-map`, the key <kbd>p</kbd> is mapped to the non-existent command `rustic-cargo-popup`. Pressing <kbd>p</kbd> in a rustic compilation buffer results in the following error:

```command-execute: Wrong type argument: commandp, rustic-cargo-popup```

Did you actually mean to map the key to `rustic-popup`?

**Comment by brotzeit** [comment]
> Did you actually mean to map the key to rustic-popup?

Yes, rustic once used the magit popup. It seems that I decided to change the name of the command when I dropped the magit popup. And I forgot to update the name in `rustic-compilation-mode-map`. Thanks for the bug report.
