### ISSUE TITLE
Rustic lsp is still picking up rls even though its set to rust-analyzer

### ISSUE THREAD

**Issue by CSRaghunandan** [brotzeit/rustic#85]
This is my configuration for rust: https://github.com/CSRaghunandan/.emacs.d/blob/master/setup-files/setup-rust.el

I use `exec-path-from-shell` as well. Upon inspecting I can see that the value of `rustic-lsp-server` is set to `rust-analyzer` and  the right path is set for the server command too.

But when I open any project, it runs `rls` instead of `rust-analyzer`. I tried setting the path of `lsp-rust-analyzer-server-command`, but that did not help too.

EDIT: found a way to fix this issue. I set `rustic-lsp-server` to `nil` and enabled `lsp` manually in a hook and that seems to have solved the issue for now. Maybe there was some changes to `lsp-rust` which caused this to break.

**Comment by brotzeit** [comment]
Thanks for opening an issue. I definitely have to make some changes here. Is it possible that lsp-mode isn't required before rustic ?

**Comment by CSRaghunandan** [comment]
> Thanks for opening an issue. I definitely have to make some changes here. Is it possible that lsp-mode isn't required before rustic ?

Yes, there is no need to run `(lsp)` to start `lsp-mode`. But right now, I'm running it manually while disabling rustic's handling of `lsp-mode`. 

Not sure what is causing `rustic` to pick up `rls` even though all the variables are set for `rust-analyzer`.

**Comment by brotzeit** [comment]
The server priority also has to be changed. I added a test https://github.com/brotzeit/rustic/commit/1fc6c56d21cc60b287351ff0ec6f707a7f81cfed

**Comment by CSRaghunandan** [comment]
Latest commit broke rustic for me.

As soon as I open a rust file, I get an error:

```
Debugger entered--Lisp error: (wrong-type-argument lsp--client nil)
  signal(wrong-type-argument (lsp--client nil))
  rustic-lsp-set-server(rust-analyzer)
  rustic-setup-lsp()
  rustic-mode()
  set-auto-mode-0(rustic-mode nil)
  set-auto-mode()
  normal-mode(t)
```

**Comment by brotzeit** [comment]
lsp-mode seems to require lsp-clients not until you open a rust file. I added a check for the server priorities that gets called before `lsp`. Thanks for the fast response.

**Comment by nmccarty** [comment]
Running on the latest melpa version (20200213.1139) is still giving me the same wrong-type-argument error. 
```
Debugger entered--Lisp error: (wrong-type-argument lsp--client nil)
  signal(wrong-type-argument (lsp--client nil))
  rustic-lsp-mode-setup()
  rustic-setup-lsp()
  rustic-mode()
  set-auto-mode-0(rustic-mode nil)
  set-auto-mode()
  normal-mode(t)
```

I've popped into the debugger, and it does, in fact, have the referenced patch applied. 

The relevant sections of my emacs config are as follows:

```emacs-lisp
  (use-package lsp-mode
    :ensure t
    :demand t
    :commands lsp
    :config
    ;;(require 'lsp-clients)
    (diminish 'lsp-mode))

  (use-package lsp-ui
    :ensure t
    :demand t
    :config
    (setq lsp-ui-flycheck-enable t)
    (define-key lsp-ui-mode-map [remap xref-find-definitions] #'lsp-ui-peek-find-definitions)
    (define-key lsp-ui-mode-map [remap xref-find-references] #'lsp-ui-peek-find-references)
    :hook 
    (lsp-mode . lsp-ui-mode))

  (use-package company-lsp
    :ensure t
    :demand t
    :config
    (push 'company-lsp company-backends))

  (use-package rustic
    :demand t
    :config
    (setq rustic-lsp-server 'rust-analyzer)
    (setq lsp-rust-analyzer-server-command '("~/.cargo/bin/ra_lsp_server"))
    (setq rustic-format-trigger 'on-save)
    (setq rustic-format-on-save t))
```

**Comment by brotzeit** [comment]
Hmmm, does it work when you uncomment `(require 'lsp-clients)` in your config and require it before rustic ? I'm no use-package expert, but the only problem is that lsp-clients isn't loaded when it's used before rustic actually launches the lsp server.

**Comment by nmccarty** [comment]
Ah yes, same error, it was actually originally uncomented but i couldn't remember why I had it in there in the first place so I commented it as a troubleshooting step. I've even tried placing it outside the use-package block, and I have all around confirmed that lsp-clients is for sure loaded before we even hit the rustic use-package

**Comment by CSRaghunandan** [comment]
> Ah yes, same error, it was actually originally uncomented but i couldn't remember why I had it in there in the first place so I commented it as a troubleshooting step. I've even tried placing it outside the use-package block, and I have all around confirmed that lsp-clients is for sure loaded before we even hit the rustic use-package

So, the error seems to happen when you had a rust project as the first `lsp` capable project. If you load another lang which has lsp support and then load a rust project, you won't get this error

I thought this was fixed in a previous commit, but looks like resurfaced?

**Comment by brotzeit** [comment]
> So, the error seems to happen when you had a rust project as the first lsp capable project.

Because `lsp-clients` is required when `lsp` runs for the first time. But I don't understand why it's not enough to require it in rustic, what we already do. If anybody has an idea...

**Comment by CSRaghunandan** [comment]
> > So, the error seems to happen when you had a rust project as the first lsp capable project.
> 
> Because `lsp-clients` is required when `lsp` runs for the first time. But I don't understand why it's not enough to require it in rustic, what we already do. If anybody has an idea...

Even my old code which used to not use `rustic` for lsp is not working anymore. I get the same error when I open a rust project.

Here is my old config for rust:
```
;; rustic-mode: Rust development environment for Emacs
;; only need to install rust-analyzer, no need to install rls or racer for lsp
;; to work for rust
;; https://github.com/brotzeit/rustic
(use-package rustic
 :init
 ;; We use the superior default client provided by `lsp-mode', not the
 ;; one rustic-mode sets up for us
 (setq rustic-lsp-server nil)
 ;; use rust-analyzer instead of rls
 (setq lsp-rust-server 'rust-analyzer)
 ;; disable rustic flycheck error display in modeline. Its redundant
 (setq rustic-flycheck-setup-mode-line-p nil)

  :hook ((rustic-mode . (lambda ()
                        (lsp)
                        (lsp-ui-doc-mode)
                        (lsp-ui-sideline-mode)
                        (lsp-ui-sideline-toggle-symbols-info)
                        (smart-dash-mode)
                        (company-mode))))
  :config
  (setq rust-indent-method-chain t)

  ;; format using rustfmt on save
  (setq rustic-format-on-save t)

  (defun my-rust-mode-hook ()
    (set (make-local-variable 'company-backends)
         '((company-lsp company-files :with company-yasnippet)
           (company-dabbrev-code company-dabbrev))))
  (add-hook 'rustic-mode-hook #'my-rust-mode-hook))

(provide 'setup-rust)

;; to disable automatic formatting of buffers, put this in `.dir-locals.el'
;; ((rustic-mode
;;   (before-save-hook . (lambda ()
;;                         (time-stamp)
;;                         (ws-butler-after-save)))))

```

**Comment by nmccarty** [comment]
I dug into the lsp-mode source a little.
I think it's caused by [this change.](https://github.com/emacs-lsp/lsp-mode/commit/4d59bded6bbba6d3bc73032305d1b3c071eb73c4#diff-0babd538a691e5e91c0bad46b93cc810)

It appears to have changed the way loading works so that, unintentionally or not, lsp-rust doesn't actually get loaded unless you explicitly request it. 

I was able to quash the error by explicitly doing a
```emacs-lisp
(require `lsp-rust) 
```
In my emacs config before loading rustic.
I unfortunately do not have time to test at the moment, but I suspect doing the same inside rustic should also resolve the issue.

**Comment by brotzeit** [comment]
@CSRaghunandan does #94 also fix this issue for you ?

**Comment by nmccarty** [comment]
Looking further into the new `lsp-mode` code, the clients are no longer actually loaded when requiring `lsp-clients` (functionality totally removed from the file).

Loading the clients automatically is now handled by a loop inside the main lsp mode function. 

Since `rustic-lsp-mode-setup` appears to gets called before `lsp`, if nothing else calls `lsp` before rustic loads, the clients are no longer guaranteed to be loaded without the additional require. 

This is a moderately confusing change from upstream, but this should adequately address it.

**Comment by brotzeit** [comment]
> Since rustic-lsp-mode-setup appears to gets called before lsp

This needs to be done in order to switch the priority of the lsp servers when you change the default server.

**Comment by CSRaghunandan** [comment]
> @CSRaghunandan does #94 also fix this issue for you ?

Yea, the latest commit seems to have fixed the issue.

Thanks
