### ISSUE TITLE
How does the babel execution work

### ISSUE THREAD

**Issue by terlar** [brotzeit/rustic#9]
Just copying the example from the README I didn't get it to work, is there any pre-steps?

```
#+BEGIN_SRC rustic :crates '(("regex" . "0.2") ("darling" . "0.1"))
fn main() {
    println!("{}", "foo");
}
#+END_SRC
```

Trying to execute this block complained about there being no `Cargo.toml` file which was correct. I touched the file inside `/private/var/folders/kt/8b_27d717w10423xq_v19v28b91d88/T/babel-SMIP9i/cargo7hXu5M`, then it proceeded to creating the `main.rs` which it refused to do, and I had to create the folder `src` then that part worked.

Then I got:
```
error: failed to parse manifest at `/private/var/folders/kt/8b_27d717w10423xq_v19v28b91d88/T/babel-SMIP9i/cargo7hXu5M/Cargo.toml`

Caused by:
  virtual manifests must be configured with [workspace]
```

Which makes me come to the conclusion that probably some other command should have been executed first? Or should it be possible to execute this kind of src block in any kind of org file?

**Comment by brotzeit** [comment]
The babel project is created with `cargo new %s --bin`. This looks to me like the cargo command isn't executed. Can you test it manually in your `org-babel-temporary-directory`.

**Comment by terlar** [comment]
Interesting, and thanks for the hint I got the following error:

```
Use `cargo init` to initialize the directory
"
"error: Failed to create project `cargoVG6wM3` at `/private/var/folders/kt/8b_27d717w10423xq_v19v28b91d88/T/babel-2ip1Bn/cargoVG6wM3`

Caused by:
  could not find '/Users/terje.larsen/.git-templates/' to stat: No such file or directory; class=Os (2); code=NotFound (-3)
```

I recently removed my `.git-templates` but still had a reference to that in my `.gitconfig`.

So I guess this is a non-issue in rustic and something I would have found out by doing any other rust command by itself.

Thanks for the help.
