### ISSUE TITLE
Org-babel execution error on Linux

### ISSUE THREAD

**Issue by carlosrogue** [brotzeit/rustic#93]
Hi, I am new to the rust world and I proceeded to install rustic as it provides babel support on Org mode. After installation, I tried to run a rust code block without luck. The error was:

```
command not found: cargo
```

But I already have cargo on my PATH: `export PATH="$HOME/.cargo/bin:$PATH"`.

Then, I found this post https://emacs.stackexchange.com/questions/34731/async-shell-command-cant-find-command and I fixed the problem with the suggested solution:

```lisp
;; Rust babel async shell command execution
(setenv "PATH" (concat (getenv "PATH") ":" (expand-file-name "~/.cargo/bin")))
(setq exec-path (append exec-path (list (expand-file-name "~/.cargo/bin"))))
```

Do I have a config problem on my machine or should this be mention as troubleshooting in the docs? Thank you very much.

**Comment by brotzeit** [comment]
I put the note at the top of the readme. You shouldn't use this solution but instead try `exec-path-from-shell`. I've tried your snippet before and I encountered some issues.
